### ISSUE TITLE
Error in fstRead when reading large data set

### ISSUE THREAD

**Issue by tgolden23** [fstpackage/fst#10]
3.7M observations of 257 variables.  Wrote to fst format without error but trying to when trying read the file back I got "Error in fstRead(fileName, columns, from, to) : 
  embedded nul in string:"

base load/save and feather both handle reads / writes of this data to file without issue.

Here is a link to the Stata version of the data set available via the web: https://pl-garlock.s3.amazonaws.com/05-Databases/GST-8002/Garlock%20Analytical%20Database/exposure%20data%20-%20all%20disease-REDACTED.dta

**Comment by MarcusKlik** [comment]
Thanks for reporting your issue. At the moment, I can't reproduce your error, with:

```r
x <- haven::read_dta(exposure data - all disease-REDACTED.dta")
write.fst(x, "1.fst")
y <- read.fst("1.fst", as.data.table = TRUE)
```

there is no error on my system, could you specify which OS (and R version) you are using?

**Comment by tgolden23** [comment]
I did not add the “as.data.table = TRUE” switch on the read command.  Will try with it.

Tim Golden
T: +1 804 775 1417

**Comment by MarcusKlik** [comment]
Hi @tgolden23 , I could not reproduce the error. If you still have any problems with your data set, please let me know!
