### ISSUE TITLE
write_fst and write.fst have inconsistent defaults of compress

### ISSUE THREAD

**Issue by renkun-ken** [fstpackage/fst#111]
I'm not sure why `write_fst` and `write.fst` have inconsistent defaults of `compress` parameter, as shown below:

```
fst::write_fst
function (x, path, compress = 30, uniform_encoding = TRUE)

fst::write.fst
function (x, path, compress = 0, uniform_encoding = TRUE)
```

**Comment by MarcusKlik** [comment]
Hi @renkun-ken, good find thanks!

Method `write.fst` will become deprecated a few versions from now, but there is no reason why the default settings should be kept at the `v0.7.2` values.

I committed [the fix](https://github.com/MarcusKlik/fst/commit/f2ee2151a188b926e9a3786479caca38e55b15db) to the release branch, so it will still be in the next CRAN version (preparing that now).

Thanks a lot!

**Comment by MarcusKlik** [comment]
Both versions of `write_fst` now have identical default compression settings
