### ISSUE TITLE
Documentation: Background threads and termination of session?

### ISSUE THREAD

**Issue by krlmlr** [fstpackage/fst#121]
I'd like to use fst in a setting where `write_fst()` is potentially the last operation in the R session. Can I be sure that the data will be safe on disk? I've searched the issues and the documentation page but couldn't find anything.

Thanks for working on fst, looking forward to the dplyr interface!

**Comment by MarcusKlik** [comment]
Hi @krlmlr, thanks for your question and love your work (though I have no idea how you can manage so many contributions :-))

Do I understand your question correctly in that you want to be sure that `fst` is not still writing data (on background threads) after the call to `write_fst` has ended (and the session after that) ? Or are you referring to backward compatibility?

The package uses `OpenMP` for it's multi-threading, and all _thread teams_ are always nicely joined again after each `OpenMP` section in the code (the mandatory synchronization points are a nice safety feature of `OpenMP`). So all API calls to the system are definitely finished at the time _write_fst_ ends (although the hardware could still be processing an already finished API call). It's a bit technical, but in short it should be no problem to end your session directly after the call :-)

On the compatibility point: from the latest release the `fst` format is backwards compatible. Any file that was created with version 0.8.0 or later will be supported indefinitely (even if that will give me headaches later on).

Yes, a `dplyr` interface would be a very nice feature addition. It will be a simple wrapper at first. But in the future it will be possible to perform chunk-based parallel operations on `fst` files,. At that point, it would be interesting to optimize the `dplyr` interface to make use of that, for example by creating parallel versions of `summarise`, `filter` and `arrange` (most difficult). I've posted a few thoughts on that in issue #108.

Thanks and any advice on implementing a parallel version of the `dplyr` interface is very welcome obviously :-)

**Comment by krlmlr** [comment]
Thanks for your quick reply. Yes, I was worried that `write_fst()` returns early with writes still pending (which might be a useful feature). Maybe it's worth mentioning specifically that writes are stable when the function returns, or add a `sync()` call that currently is a no-op but might do useful things later?

The back-compatible file format is great, too.

**Comment by MarcusKlik** [comment]
Hi @krlmlr, [the documentation](https://github.com/fstpackage/fst/blob/develop/R/fst.R#L25-L32) for `write_fst()` was updated to reflect that reads and writes are stable when these methods finish.

Thanks again for the pointers!
