### ISSUE TITLE
ITime column support

### ISSUE THREAD

**Issue by Giqles** [fstpackage/fst#126]
It seems like ITime format columns are meant to be supported (eg, #82, #85, #17) but they don't seem to work correctly for me. Eg,

```r
dt <- data.table(test = as.ITime(1:10, origin = "1970-01-01")) 
str(dt)
# Classes ‘data.table’ and 'data.frame':	10 obs. of  1 variable:
# $ test:Class 'ITime'  int [1:10] 1 2 3 4 5 6 7 8 9 10
# - attr(*, ".internal.selfref")=<externalptr>  
f <- tempfile()
write.fst(dt, f)
fst.metadata(f)
# <fst file>
# 10 rows, 1 columns (/tmp/RtmpuKW8XC/file9c394a829be5)
* 'test': ITime 
dt <- read.fst(f, as.data.table = T)
str(dt)
# Classes ‘data.table’ and 'data.frame':	10 obs. of  1 variable:
# $ test: int  1 2 3 4 5 6 7 8 9 10
# - attr(*, ".internal.selfref")=<externalptr>
```

**Comment by MarcusKlik** [comment]
Hi @Giqles, thanks for reporting that! Indeed, I see there is an attribute-test missing in the integer vector factory, well spotted. I will fix that as soon as possible!

**Comment by MarcusKlik** [comment]
The `fst` format allows for two `ITime` types; the `integer` and the `double` variant:

``` r

library(data.table)

x = as.ITime(1:10)
typeof(x)
#> [1] "integer"

x = 1.2:10.3
class(x) <- "ITime"
typeof(x)
#> [1] "double"
```

They are encoded with the _INT_32_TIME_OF_DAY_SECONDS_ and _DOUBLE_64_TIME_OF_DAY_SECONDS_ attributes [this code](https://github.com/fstpackage/fst/blob/develop/src/fstcore/interface/ifstcolumn.h#L74-L79). But upon reading, these attributes are not checked, so a default `integer` column is constructed.

**Comment by MarcusKlik** [comment]
The `ITime` attribute is now correctly implemented and available in the `dev` version, thanks for submitting your issue!
