### ISSUE TITLE
CRAN archival: alternative repository

### ISSUE THREAD

**Issue by HughParsonage** [fstpackage/fst#130]
As the package maintainer of `heims`, was sorry to learn that `fst` is liable to be archived. From my scan of the issues, this is due to a change in the LZ4 library that's yet to be released. Is my understanding correct? Are you able to provide an `Additional_repository` for `fst` in the meantime (say through the `drat` package)?

I've had no problems with `fst` at all, though of course CRAN's policies are generally there for a good reason. Hope to see you back there soon!

**Comment by MarcusKlik** [comment]
Hi @HughParsonage (and @leeper for the `rio` package), indeed the `fst` package had problems building on the CRAN `dev` branch. But I have just pushed a new `fst` version to CRAN that addresses this issue (v0.8.4). The latest version of `LZ4` is included in that version of the package in which the Clang 6.0.0 errors are fixed.

I will keep you posted on the progress of the submission, apologies for the delay!

**Comment by MarcusKlik** [comment]
(I guess I didn't realize CRAN would be sending warnings out before the deadline they gave me ;-))

**Comment by HughParsonage** [comment]
No apology necessary. It's a fantastic package but I understand that it works at such a low level that it is very difficult to maintain.

I think Prof. Ripley's message was just as a courtesy to us to prepare our packages should `fst` be unable to be fixed. It's understandable that they need to mitigate against you being unable to patch the issues to preserve the archive.

**Comment by MarcusKlik** [comment]
Yes, and that's fully understandable off course with more than 10000 packages on CRAN.
Indeed, there are challenges with `fst`: it uses OpenMP and three C++ libraries (`LZ4`, `ZSTD` and `fstlib`). Also, it works for little-endian systems only (at the moment). I decided to wait a little bit before introducing SIMD instructions :-)

The `fstlib` library I can update myself in case of issues, but with `LZ4` I preferred to address the problem with the authors themselves (and I'm also not allowed to change code in that library and put it in `fst`).

Thanks for your patience and for using `fst` in `heims`!

**Comment by leeper** [comment]
Great. Thanks for the update. I'll keep an eye on this.

**Comment by MarcusKlik** [comment]
Hi @HughParsonage and @leeper, a few builds are still due, but I can safely say from the [CRAN checks](https://cran.r-project.org/web/checks/check_results_fst.html) that yesterdays submission won't have any problems on the `dev` braches.

Thanks!

**Comment by MarcusKlik** [comment]
Closing this issue, all relevant CRAN builds are passing now, thanks @HughParsonage  and @leeper!
