### ISSUE TITLE
Request: set number of threads with options()

### ISSUE THREAD

**Issue by karldw** [fstpackage/fst#132]
fst currently allows the user to set the number if threads with the `threads_fst` function, and the default number if threads is the number of logical cores on the system. It would be convenient (for me, hopefully for others) if the number of threads could be set with an option.  Using an option, instead of a function in the package, allows for Rprofile.site files to set the option without loading the fst package.

I'm copying the name and idea from the lfe package, which has an `lfe.threads` option.

```r
# What I'd like:
options(fst.threads = 2L)

# What's currently necessary:
if (requireNamespace("fst", quietly = TRUE)) {
  library(fst)
  fst::threads_fst(2L)
}
```

 (fst will overwrite the value of `threads_fst` if you `library(fst)` after setting the number of threads, so an Rprofile has to `library(fst)` to make the setting stick.)

Let me know what you think and I can write a pull request!

**Comment by MarcusKlik** [comment]
Hi @karldw, thanks for your feature request, I think that's an excellent idea!

We could test for the option in the `onAttach` method and set it accordingly [here](https://github.com/fstpackage/fst/blob/develop/R/onAttach.R#L56), nice.

What do you mean exactly by `library(fst)` overwriting the setting? If I do:

``` r
library(fst)

# number of threads set automatically to number of logical cores
threads_fst()
#> [1] 8

# set manually and display
threads_fst(2)
#> [1] 8
threads_fst()
#> [1] 2

# use library again
library(fst)

# Still at 2 threads
threads_fst()
#> [1] 2
```

the `onAttach` method is called only once, so the number of threads set previously will not be overwritten, or is that not what you are referring to?

thanks, pull requests are very welcome!

**Comment by karldw** [comment]
Ah, sorry, that was unclear.  I meant that the `.onAttach` code overwrites the number of threads if `threads_fst` is called before the package is attached.

```r

# number of threads set automatically by (I think) omp_get_max_threads
fst::threads_fst()
#> [1] 4

# set manually and display old value
fst::threads_fst(2)
#> [1] 4

# looks good
fst::threads_fst()
#> [1] 2

library(fst)
#> fst package v0.8.4
#> (OpenMP detected, using 4 cores)

# back to using 4 cores :(
fst::threads_fst()
#> [1] 4
```
One way to fix this would be for to move the `threads_fst` call from `.onAttach` to `.onLoad`. 

It will save some headaches if this new `fst.threads` option is always in sync with the `threads_fst` function. 
First, that requires `threads_fst` to update the option, which is easy.
More difficultly, since users can change the option at any time, every fst function would have to check the value of the `fst.threads` option and call `threads_fst` if they're out of sync. (It's necessary to call `threads_fst`, rather than immediately use the value of `fst.threads`, because you need to tell the OpenMP code how many cores to use.)

If you see a cleaner way to do this, or think it's no longer worth it, let me know!

Side note, the comment [here](https://github.com/fstpackage/fst/blob/8b9f6860f73b26337efadcdc7ad2242b58d230f1/R/onAttach.R#L52) confuses me. It seems to say the code will prefer physical core count, but then it uses the logical core count. Am I reading that right?

**Comment by MarcusKlik** [comment]
Hi @karldw, thanks and you're right, the comment is very confusing, I will change it!

The `dev` version was using the number of physical cores as the default until I noticed that there is actually a performance gain when hyper-threading with double the amount of cores. At that point the default was changed :-). 

I thinking syncing the option might be problematic. What happens for example if you're in a forked session and the option is changed? To avoid switching to multiple threads in that case, additional checks will be needed. Perhaps it's fine if the number of threads is only read from the options when the package is loaded and that the user can change it afterwards (if required). Also, the package startup message could mention that the number of threads was set from the `fst.threads` option:

```r
#> (OpenMP detected, setting to 4 cores from option fst.threads)
```

Just out of curiosity, what is your use-case for needing to change the number of threads to a lower setting?

**Comment by karldw** [comment]
Hi @MarcusKlik

Great, thanks!

Ah, I hadn't considered all the complications.  I agree, keeping the option synced is more effort than it's worth.

I'm interested in using a lower number of threads because I'm working on a shared machine with 32 logical cores. Rather than using tying up all of them (with [decreasing marginal returns](https://github.com/fstpackage/fst/blob/develop/README-multi-threading-1.png) for more threads), I want to use only a few.
