### ISSUE TITLE
Updated from 0.7.3, can't load fst files using "old_format = TRUE" argument

### ISSUE THREAD

**Issue by PoGibas** [fstpackage/fst#135]
After update from **0.7.3** (2017-10-30) to **0.8.4** (current version) I can't load `fst` files (that were created with **0.7.3**). Error message is:
```
Error in fstretrieve(fileName, columns, from, to, old_format) : 
  Unrecognised file type, are you sure this is a fst file?
```
Tested this with 0.8.0 and 0.8.2, but getting same error. Tested with 0.7.2 and this produced `Error in fstRead(fileName, columns, from, to) : std::bad_array_new_length`  message. 

How can I solve this problem?

**Comment by MarcusKlik** [comment]
Hi @PoGibas, I'm sorry you have this problem. It seems you saved the file using a `dev` version of `fst` and are now trying to read it with a CRAN version. Backwards compatibility for that is guaranteed from version `v0.8.0` onwards, but not before.

I think the best you can do is clone this repository, use git to set the repository back to 2017-10-30 and then build the package. You should be able to load your file and write it with `saveRDS` for example.

Then you can update to the latest CRAN version and re-write the file again. Apologies for the inconvenience!

If you have Windows, you could try to use the package compiled by [AppVeyor](https://ci.appveyor.com/project/MarcusKlik/fst-6acb8/build/1.0.55/artifacts)

please let me know if that works for you!

**Comment by PoGibas** [comment]
Confirming that after reverting back to **0.7.3** (commit 1c97759) I can load `fst` files. As suggested: 

1. Will save data to `RDS` format
2. Upgrade to current `fst` version
3. Will save data to `fst` format

**Comment by MarcusKlik** [comment]
Hi @PoGibas, thanks for sharing that. Good to hear you have your data back!

New versions of `fst` will support files that you write with (CRAN) version `v0.8.0` or later indefinitely, so you shouldn't have this kind of problems anymore in the future.
