### ISSUE TITLE
Error when reading from network drive

### ISSUE THREAD

**Issue by xiaodaigh** [fstpackage/fst#136]
I can write to network drives but when I am reading from the network drive I get this error
```r
Error in normalizePath(path.expand(path), winslash, mustWork) : 
  path[1]="dt.fst": Access is denied
```
However, if I copy the fst file to C drive then it works fine. 

I am running Windows 7 and the network is set up in such a way that I have access to 

> \\network\\drive\\folder\folder1 

but I have no access to

> \\network\\drive\\folder\

So I can actually see further down in the tree hierachy but not the level up. Hopefully this helps identify the bug, as I can't produce a MWE due to the difference in network architecture.

**Comment by MarcusKlik** [comment]
Hi @xiaodaigh, thanks for reporting the issue!

In `read_fst()`, method `normalizePath()` is [used on the _path_ argument](https://github.com/fstpackage/fst/blob/develop/R/fst.R#L159) and not on the directory above, so I'm a bit puzzled by the error (usage is identical to `write_fst()`).

If you call `normalizePath()` yourself on the newly created `fst` file, does that work as expected?

thanks

**Comment by MarcusKlik** [comment]
Hi @xiaodaigh, the difference is that I use _mustWork = TRUE_ for `read_fst()`, while I use _mustWork = FALSE_ for `write_fst()`. The error can be reproduced locally by using `normalizePath()` and remove access to the top level (local) directory.

Perhaps a better approach would be to use `normalizePath(path, mustWork = FALSE)` and then to check the existence of the `fst` file with `file.exists()`:

```r
x <- normalizePath("1/2/data.fst", mustWork = FALSE)
file.exists(x)
#> [1] TRUE
```

**Comment by MarcusKlik** [comment]
Hi @xiaodaigh, I just committed [a fix](https://github.com/fstpackage/fst/commit/7cdf697fe1f8b63970d8a0d4b80516bc3d8d4314), could you retest writing and reading your `fst` file with the latest `dev` version?

thanks a lot!
