### ISSUE TITLE
More descriptive error message for incorrect column selections

### ISSUE THREAD

**Issue by MarcusKlik** [fstpackage/fst#138]
by mail, from Jean-Luc:

currently, the following incorrect column selection leads to an error message that's not very descriptive:

```r
# write some data
temp_file <- tempfile()
fst::write.fst(data.frame(A = 1:26, B = LETTERS), temp_file)
 
# incorrect column selection
fst::read_fst(temp_file, columns = "b")
#> Error in fst::read_fst(temp_file, columns = c("B", "a")) : 
#>  Selected column not found.
```

It would be nice to have the error message reflect the incorrect column name (_a_ in this case).

**Comment by Moohan** [comment]
Any update on this, I was just about to post a new request for it, as I'm having issues and the error message could definitely be more helpful! 😄

**Comment by MarcusKlik** [comment]
Hi @Moohan, thanks for your request.

I've updated the error message, an incorrect column selection now leads to:

``` r
# write some data
temp_file <- tempfile()
fst::write.fst(data.frame(A = 1:26, B = LETTERS), temp_file)

# incorrect column selection
fst::read_fst(temp_file, columns = c("b", "A"))
#> Error in fst::read_fst(temp_file, columns = c("b", "A")): Column 'b' not found
```

short but informative 😸
