### ISSUE TITLE
fst_table object should return one-column data.frame as vector, as for data.frames

### ISSUE THREAD

**Issue by martinblostein** [fstpackage/fst#141]
To match data.frame functionality, fstfile[x, 'a'] should return the vector a, not a single-column data.frame:

```
x <- data.frame(a = 1:4, b = 1:4)
file_path <- tempfile()
fst::write_fst(x, file_path)
fstfile <- fst::fst(file_path)

x$a # returns vector
fstfile$a # returns vector

x[, 'a'] # returns vector
fstfile[, 'a'] # returns df
```

**Comment by martinblostein** [comment]
Side note: `fst::read_fst(file_path, columns = 'a')` returns a single column data.frame. In my opinion, this is preferred, as the argument to read_fst is called "columns", and if you specify one column, you ought to get a data.frame with a single column.

**Comment by MarcusKlik** [comment]
Hi @martinblostein, thanks for reporting that!
Yes, the bracket operators should mimic the `data.frame` functionality so it would be better to return a vector (however unpreferred that might be :-))

Will fix as soon as possible, thanks!

**Comment by gsgxnet** [comment]
Probably to late to comment - anyhow:

There is much discussion whether that implicit conversion of a df to a vector is really reasonable. It seems to be kept only for backward compatibilty.

The big problem is, if the columns selected are a computed at runtime expression you get a very unreliable behavior of such a `fstfile[, cols]` If cols contains more than one column then your result is a df, if only 1 it is a vector. Very inconsistent. 

I would not copy that ugly df behavior blindly. Okay if optional.

**Comment by MarcusKlik** [comment]
Hi @gsgxnet, thanks for your comment! I fully agree with you that the behavior for _one-column data frames_ is not very consistent and is prone to errors. However, that behavior is now part of the language and is also how e.g. `data.table` has implemented it:

``` r
data.table::data.table(X = 1:10, Y = LETTERS[1:10])[, X]
#>  [1]  1  2  3  4  5  6  7  8  9 10
```

So (perhaps unfortunately) I think `fst` should stick to that as well because that's what users will expect, don't you think?

**Comment by martinblostein** [comment]
It's not great, but it is unfortunately the expected default behaviour in R. It's the same with matrices:
```
x <- matrix(1:4, 2, 2)
x[,1]
#> [1] 1 2
x[1,]
#> [1] 1 3
```

The 'good' news is that the `drop` argument to `[` can be used to ensure that the output is a `data.frame` or matrix no matter what. We could implement that option.

**Comment by MarcusKlik** [comment]
Yes, good idea, there is no reason to keep our [current warning](https://github.com/fstpackage/fst/blob/develop/R/fst_table.R#L347), we might as well return a `data.frame` when requested, thanks @martinblostein and @gsgxnet!

**Comment by gsgxnet** [comment]
Yes I agree having the `drop` argument seems to be the best compromise of standard adherence and development of R scripts/functions which must have a defined reliable result format.

I reread the `data.table` 1.11 FAQ and tutorial and it I found at least 3 options to force the result to be a data.table all the times:
`dt[, list(X)]`  
`dt[, .(X)]`   
`dt[, "X"]` 
but it does not really support `dt[, X, drop=FALSE]`.  That argument is only available as `data.frame` inherited but does not force a 1 column `data.table` result.

**Comment by MarcusKlik** [comment]
Hi @martinblostein and @gsgxnet, following #193, I've revisited this issue on the _drop_ parameter. It now follows base `R` behavior, thanks again for pointing out the issue!
