### ISSUE TITLE
Fix all valgrind warnings

### ISSUE THREAD

**Issue by MarcusKlik** [fstpackage/fst#152]
The current `valgrind` warnings lead to confusion and extra work during a CRAN submission. They result from writing uninitialized bytes to file, which is done for performance (initializing takes some time).
These issues need to be resolved in the next release, for example by creating an option _fst_uninialized_bytes_ which can be set to `FALSE` to make sure all buffers are initialized before writing (default: `TRUE`)

**Comment by MarcusKlik** [comment]
I've located the `valgrind` warnings [reported on CRAN](https://www.stats.ox.ac.uk/pub/bdr/memtests/valgrind/fst/fst-Ex.Rout) and all of them are caused by uninitialized bytes being written to disk. Those bytes are now initialized to zero using `memset()` which should solve the `valgrind` issues. CRAN maintainers have asked to submit the fixes as soon as possible, so a `fst` package version `v0.8.8` will make it's way to CRAN soon.

**Comment by russellpierce** [comment]
Checking in on this because CRAN is at v0.8.8. Does that mean you've already resolved this issue, or was it pushed to a later release?

**Comment by MarcusKlik** [comment]
Hi @russellpierce, thanks for spotting that! Indeed, the `valgrind` warnings have been fixed in `v0.8.8` on request of the `CRAN` maintainers (mainly in [this commit](https://github.com/fstpackage/fst/commit/cea2d10c14713d6fef18d73e711af55fcde745ef)). I will close this issue and label it with the correct milestone, thanks!
