### ISSUE TITLE
Attributes are serialized in fst binary format

### ISSUE THREAD

**Issue by MarcusKlik** [fstpackage/fst#17]
All attributes are stored in the `fst` file format. Complex types can be stored by using R's native serialization mechanism and compressing with the fast LZ4 or ZSTD for large attribute objects. It might be a good idea to store the col.names atribute as a normal column for speed. Allowing attributes would facilitate adding user-defined metadata to a `fst` file.

**Comment by arunsrinivasan** [comment]
Great work! Preserving *column*'s (e.g., `IDate` or `ITime` objects in data.table which are internally just integers)  custom class info  as well as any other additional attributes (including custom class) would be very useful.

**Comment by MarcusKlik** [comment]
Thanks @arunsrinivasan , and love your work on the `data.table` package! Indeed, serializing custom attributes would be a nice addition. But it might also introduce some unexpected behavior when only a subset of the rows is read from file. For example, the attributes of a time series data column is not valid anymore when a subset of that column is taken. So, I'm still not sure whether it would be better to:

* serialize custom attributes and just omit them when a subset of rows is read from file _or_
* only serialize attributes of 'known' classes and just implement many of those classes (such as the `IDate` and `ITime` classes you mentioned.

If you have any ideas on that they are very welcome!

**Comment by arunsrinivasan** [comment]
Thank you very much! 

How about having a *whitelist* (or a *blacklist* -- I guess it'll be smaller) of column classes that could be preserved irrespective of the number of rows? The check could then happen only when a subset of rows is requested.. Basically I'm going with your 2nd option, but in a way that could be made into the first one if it proves to be too cumbersome..

**Comment by MarcusKlik** [comment]
Thanks, yes, so always serialize the attribute and return it when a full column is requested. On a subset, just return attributes for classes that are on the whitelist. For common classes that require a mapping (like time series) I could even do that on the fly. Perhaps attributes can be forced onto subsets with an argument `force_attribute = TRUE` or similar. Thanks, I will implement the attribute feature like that!

A small test on `data.table` reveals that no mapping on attributes is performed for a time series, but they are copied on sub-setting:

```r
timeseries <- ts(LETTERS, start=c(2012, 1), end=c(2017, 2), frequency = 12)
dt <- data.table(A = timeseries)

timeseries[2:40]  # attribute lost

 [1] "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S" "T" "U" "V" "W" "X" "Y" "Z" "A" "B" "C" "D" "E"
[31] "F" "G" "H" "I" "J" "K" "L" "M" "N"

dt[, A]  # attributed retained

     Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec
2012   A   B   C   D   E   F   G   H   I   J   K   L
2013   M   N   O   P   Q   R   S   T   U   V   W   X
2014   Y   Z   A   B   C   D   E   F   G   H   I   J
2015   K   L   M   N   O   P   Q   R   S   T   U   V
2016   W   X   Y   Z   A   B   C   D   E   F   G   H
2017   I   J   

dt[3:20, A]  # attribute copied

Time Series:
Start = c(2012, 1) 
End = c(2017, 2) 
Frequency = 12 
 [1] C D E F G H I J K L M N O P Q R S T
Warning messages:
1: series is corrupt: length 18 with 'tsp' implying 62 
2: series is corrupt: length 18 with 'tsp' implying 62 
```

**Comment by MarcusKlik** [comment]
Hi @arunsrinivasan, following our earlier discussion in this thread, `fst` now has a three step system to distinguish the various column types:

1. A [main type specifier](https://github.com/fstpackage/fst/blob/develop/src/fstcore/interface/ifstcolumn.h#L60-L70) that maps to the underlying data type
2. A [column attribute](https://github.com/fstpackage/fst/blob/develop/src/fstcore/interface/ifstcolumn.h#L75-L95) that further specifies the exact type (e.g. `IDate` and `ITime` are both `integers` as you mention earlier but have attributes `INT_32_DATE_DAYS` and `INT_32_TIME_OF_DAY_SECONDS` to distinguish them). That means that when a `fst` file is read with a (future) `Python` wrapper, it will have to map to a `Python` version of the `ITime` class.
3. A [timescale](https://github.com/fstpackage/fst/blob/develop/src/fstcore/interface/ifstcolumn.h#L108-L118) for time-related types or a [scale](https://github.com/fstpackage/fst/blob/develop/src/fstcore/interface/ifstcolumn.h#L47-L55) for general types.

For example, a `nanotime` column is implemented as a `INT_64` type with attribute `INT_64_TIME_SECONDS` and a scale `NANOSECONDS`.

This three-layered systems covers all types currently implemented and for custom data an annotation can be used for each column (currently only used to store the time-zone of the `POSIXct` type).
 
Any additional thoughts on implementing more types are very welcome! Custom user-defined attributes (our earlier discussion) are difficult however, because `fst` now has a language independent `C++` core and a custom attribute in one language (`R`) doesn't necessarily have any meaning in another (`Python`). 

Time series are not implemented yet and it would need a special way of scaling the attributes when data is randomly selected from the table (to re-scale the start- and end- time). If important to users, that could be done by storing the offset and delta-time in the annotation for example and re-calculate them when a (row-) subset of the table is selected.

I think I will close this issue for now, when new column types have to be implemented, we could re-open a new issue for that, thanks a lot for your idea's!
