### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by bwlewis** [fstpackage/fst#176]
I get:

```
set.seed(1);x=fst::compress_fst(serialize(runif(2^29),NULL), "LZ4")

 *** caught segfault ***
address (nil), cause 'unknown'

Traceback:
 1: fstcomp(x, compressor, as.integer(compression), hash)
 2: fst::compress_fst(serialize(runif(2^29), NULL), "LZ4")
```
and the same with the ZSTD compressor:

```
set.seed(1);x=fst::compress_fst(serialize(runif(2^29),NULL), "ZSTD")

 *** caught segfault ***
address (nil), cause 'unknown'

Traceback:
 1: fstcomp(x, compressor, as.integer(compression), hash)
 2: fst::compress_fst(serialize(runif(2^29), NULL), "ZSTD")
```

with:
```
R.version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          5.1                         
year           2018                        
month          07                          
day            02                          
svn rev        74947                       
language       R                           
version.string R version 3.5.1 (2018-07-02)
nickname       Feather Spray
```

Not sure exactly where the problem is...I don't think it's R or the compression library because this works on the same system, using the old  lz4 https://github.com/bwlewis/lz4 package that I hope fst will replace eventually...
```
x = lz4::lzCompress(serialize(runif(2^29), NULL))
```

**Comment by MarcusKlik** [comment]
Hi @bwlewis, thanks a lot for reporting the issue!

You're allocating a vector larger than 4 GB, so it looks like a problem with (64-bit) memory addressing. Does the problem occur if you use:

```r
set.seed(1)
blob <- serialize(runif(2^28), NULL)
x <- fst::compress_fst(blob, "LZ4")
``` 

your package is very nice and uses `LZ4` to compress a vector in one go, doesn't it? That's different from `fst`, because `fst` divides the `raw` vector in smaller blocks and then compresses each of them separately. Perhaps you should keep your package or expand it with some additional compression libraries (`snappy`, `brotli`, ?)  :-)

**Comment by MarcusKlik** [comment]
Hi @bwlewis, I've updated the `fstlib` library and the latest version contains a fix for your issue. The following code now runs correctly:

```r
# compress raw vector > 4GB
set.seed(1)
blob <- serialize(runif(1e6 + 2^29), NULL)

# vector size in GB
2^-30 * as.numeric(object.size(blob))
#> [1] 4.007451

# in-memory compression with LZ4 and ZSTD
x_lz4 <- fst::compress_fst(blob, "LZ4")
x_zstd <- fst::compress_fst(blob, "ZSTD")
```

and the performance is still very good with large vectors:

``` r
# raw vector > 4GB
set.seed(1)
blob <- serialize(sample(1:100, 1e6 + 2^30, replace = TRUE), NULL)

# vector size in GB
size <- 2^-30 * as.numeric(object.size(blob))

# in-memory compression with LZ4 (fastest setting)
bench <- microbenchmark::microbenchmark(
  x_lz4 <- fst::compress_fst(blob, "LZ4", compression = 0),
  times = 100
)

# median time in seconds
secs <- 1e-9 * median(bench$time)

# GB /s
size / secs
#> [1] 2.75691
```

So, that's a compression speed of 2.75 GB/s on my 6-core laptop (i7-8750H) (note that I have replaced your fully random data with a small sample to be sure that data can be heavily compressed).

It would be great if you could test your example on the latest `dev`:

```r
devtools::install_github("fstpackage/fst", ref = "develop")
```

thanks again for reporting the problem!

**Comment by bwlewis** [comment]
Awesome, thanks works now.
