### ISSUE TITLE
Inventory of fst files in a folder - feature request

### ISSUE THREAD

**Issue by ghost** [fstpackage/fst#187]
I have a feature request. It would be great to be able to have a function which inventories the "fst" files in a folder (or folder tree), and assigns to each file a variable name to each fst file in the inventory, e.g.

ft <- fst(path)
print(ft)

but for a folder, e.g.:
```

library(tidyverse)
library(fs)
library(fst)
data(diamonds)

fs::dir_create(here::here("data"))
diamonds %>% group_split(color) %>% 
  walk(~.x %>%  write_fst(path = paste0("data/diamonds_",unique(.x$color),".fst")))

junk <- dir_info(here::here("data"), glob="*.fst") %>% select(path) %>% 
  mutate(
    fst_name = str_sub(basename(junk$path),1,-5),
    path_name = path) 

```

What I would want is for junk$fst_name to be the variable associated (via fst::fst) with the junk$path file.

I suspect there is a purrr:: walk or purrr::walk2 way to do this, but the syntax is escaping me. The above example does assume that the basenames for the files do not repeat, and that might be an assumption that is violated if dir_info() was invoked recursively.

Great package. So helpful. Thank you.

**Comment by xiaodaigh** [comment]
You can already do this. I used `data.table` but you should get the gist of it; the trick is to use `assign` to assign variables names to the global environment. Check the 

```r
library(data.table)
setDT(diamonds)

diamonds[,{write_fst(.SD,paste0("data/diamonds_",as.character(.BY[[1]]),".fst"));NULL}, color]

junk <- dir(here::here("data")) %>% 
  purrr::walk(function(path) {
    assign(path, read_fst(file.path("data", path)), envir = .GlobalEnv)
  })

ls()

#[1] "diamonds"       "diamonds_D.fst" "diamonds_E.fst"
#[4] "diamonds_F.fst" "diamonds_G.fst" "diamonds_H.fst"
#[7] "diamonds_I.fst" "diamonds_J.fst" "junk"   
```

If you want to manipulate these files simultaneously you might find https://github.com/xiaodaigh/disk.frame useful

**Comment by ghost** [comment]
Thanks. The magic was in the assign. I'll work it up for a non-DT example
and post just to close  the documentation. Many thanks!

Closed, with thanks.

**Comment by ghost** [comment]
library(data.table)
library(fst)
library(tidyverse)
library(fs)

data(diamonds)

fs::dir_create(here::here("data"))
diamonds %>% group_split(color) %>% 
  walk(~.x %>%  write_fst(path = paste0("data/diamonds_",unique(.x$color),".fst")))

junk <- dir(here::here("data")) %>% 
  purrr::walk(function(path) {
    assign(path, read_fst(file.path("data", path)), envir = .GlobalEnv)
  })

ls()

table(diamonds_D.fst$cut)

**Comment by ghost** [comment]
Above is trivial adaptation for non data.table approach. Many thanks.

**Comment by MarcusKlik** [comment]
Hi @aetiologicCanada and @xiaodaigh , thanks for sharing your solutions!

In my experience using `assign()` or equivalent methods is almost always very bad for reproducibility and tracking bugs. It's a form of _meta-programming_ or _programming on the language_ that can lead to unpredictable results :-).

How about filling a list:

```r
library(ggplot2)  # contains diamonds
library(data.table)
library(fst)

# get dataset
data(diamonds)

# write a couple of fst files
setDT(diamonds)[, {write_fst(.SD,paste0("diamonds_", as.character(.BY[[1]]),".fst"));NULL}, color]

fst_files <- dir(".", ".fst")  # list of fst files

# fill a list
diamond_list <- fst_files %>%
  lapply( function(path) {
    read_fst(file.path(path))
  })

names(diamond_list) <- basename(fst_files)  # name list
```

this way, you won't clutter your global environment and can always compute on the data in the list later on:

```r
# show number of rows
sapply(diamond_list, nrow)

# bind the data together again
all_data <- bind_rows(diamond_list)

# verify the result
nrow(all_data) == sum(sapply(diamond_list, nrow))
```

this would be much harder to do if you have a (a-priory unknown) amount of variables in your global environment...
