### ISSUE TITLE
Inconsistent conversion to vector

### ISSUE THREAD

**Issue by jllipatz** [fstpackage/fst#193]
Hello,

Should it be possible to get a behaviour similar to the R base 'drop'  parameter? 

`df <- data.frame(x=LETTERS,y=1:26)
write_fst(df,"test.fst")
fst("test.fst") %>% .[1:10,"x",drop=FALSE] # a vector, 'drop' is ignored
fst("test.fst") %>% .[,"x",drop=TRUE] # a data.frame 'drop' is rejected with a message

Best regards

Jean-Luc

**Comment by MarcusKlik** [comment]
Hi @jllipatz, thanks for pointing out that inconsistency!

Indeed, the current behavior is not what you would expect (on `dev`):

``` r
library(fst)

df <- data.frame(x = LETTERS, y = 1:26)
write_fst(df, "test.fst")

x <- fst("test.fst")

# row subset, no drop
x[1:10, "x", drop = FALSE]
#>  [1] A B C D E F G H I J
#> Levels: A B C D E F G H I J K L M N O P Q R S T U V W X Y Z

# all rows, no drop
x[, "x", drop = FALSE]
#>    x
#> 1  A
#> ...
#> 26 Z

# row subset, drop
x[1:10, "x", drop = TRUE]
#> Warning: drop ignored
#>  [1] A B C D E F G H I J
#> Levels: A B C D E F G H I J K L M N O P Q R S T U V W X Y Z

# all rows, drop
x[, "x", drop = TRUE]
#> Warning: drop ignored
#>    x
#> 1  A
#> ...
#> 26 Z
```

the expected behavior is to always assume _drop = FALSE_ and throw a message in other cases. But I agree it would be more clear to the user when the _drop_ argument is implemented in a manner consistent with base `R` (see also #141).

thanks!

**Comment by MarcusKlik** [comment]
Hi @jllipatz, I've corrected the _drop_ behavior, your code now runs as:

``` r
library(fst)

df <- data.frame(x = LETTERS[1:5], y = 1:5)
write_fst(df, "test.fst")

x <- fst("test.fst")

# row subset, no drop
x[2:3, "x", drop = FALSE]
#>   x
#> 1 B
#> 2 C

# all rows, no drop
x[, "x", drop = FALSE]
#>   x
#> 1 A
#> 2 B
#> 3 C
#> 4 D
#> 5 E

# row subset, drop
x[2:3, "x", drop = TRUE]
#> [1] B C
#> Levels: A B C D E

# all rows, drop
x[, "x", drop = TRUE]
#> [1] A B C D E
#> Levels: A B C D E
```

thanks again for pointing out the issue!
