### ISSUE TITLE
Potential Compatibility Issue

### ISSUE THREAD

**Issue by dipterix** [fstpackage/fst#195]
Hi, I'm writing a package that needs fast IO. I have two choices `vroom` or `fst` and I select `fst` because it is twice as fast as `vroom`. However, I'm worried about the potential compatibility issue for`fst` package. 

For example, if my data is generated using old versions (0.8.10), will it be possible that the future versions don't support the data format? (like 0.9.0 doesn't support 0.7.X)

Thanks.

**Comment by MarcusKlik** [comment]
Hi @dipterix, thanks for your question!

There's no need to worry, all _fst_ files generated with versions 0.8.0 or higher will be supported by later versions of the package, [as stated](https://github.com/fstpackage/fst/blob/develop/README.Rmd#L177) in the project README.

The earlier (beta) format didn't contain hashes for internally stored metadata and that made the format more vulnerable. The current format is properly hashed and versioned and therefore backwards compatibility is much easier to maintain.

Hope that helps, good luck with your package!

**Comment by dipterix** [comment]
That sounds great! Thanks!
