### ISSUE TITLE
FST color ANSI issue

### ISSUE THREAD

**Issue by muschellij2** [fstpackage/fst#198]
Trying to have `fst` in a vignette and print out the output from `fst::fst`, but ANSI colors don't work right with PDF:
Offending code is: https://github.com/fstpackage/fst/blob/develop/R/fst_table.R#L222
```r
   if (!"crayon" %in% loadedNamespaces()) {
        if (!requireNamespace("crayon", quietly = TRUE)) {
            color_on <- FALSE
        }
        else {
            if (!crayon::has_color()) {
                color_on <- FALSE
            }
        }
    }
```

So if `crayon` is not loaded (`!"crayon" %in% loadedNamespaces()`), then will check if `crayon` is installed.  If it is installed, but no color, then `color_on = FALSE`.  I believe this is the only way to get `color_on = FALSE`, which means I need to run:

```
options(crayon.enabled = FALSE)
```

Just unclear why not just have:
```r
        if (requireNamespace("crayon", quietly = TRUE)) {
            color_on = crayon::has_color()
        }
```
to simplify the code?  It seems as though if `crayon` is loaded, regardless of whether color is wanted, then it will try to do put color given the current code.

**Comment by MarcusKlik** [comment]
Hi @muschellij2, thanks for spotting that!

Indeed, when there is no `crayon` package, the coloring was turned _on_ instead of _off_. The code now reads:

``` r
  color_on <- FALSE

  if (requireNamespace("crayon", quietly = TRUE)) {
    color_on <- crayon::has_color()
  }
```

so the default is to turn off coloring except when `crayon` is installed and can verify the terminal has coloring.

thanks!
