### ISSUE TITLE
A strange warning message

### ISSUE THREAD

**Issue by waynelapierre** [fstpackage/fst#203]
My code and warning message is as below:
```
require(fst)
Loading required package: fst
fst package v0.9.0
(OpenMP detected, using 4 threads)
Warning message:
In setnrofthreads(nr_of_threads) :
  '.Random.seed[1]' is not a valid integer, so ignored
```

**Comment by MarcusKlik** [comment]
Hi @waynelapierre, thanks for reporting your problem!

Could you try running the following code on your system to see if you can trigger the error:

``` r
.Random.seed[1]
#> [1] 10403
```

**Comment by waynelapierre** [comment]
I rebooted my computer and this issue just disappeared. Thanks for your reply!

**Comment by MarcusKlik** [comment]
great, thanks!
