### ISSUE TITLE
update to 0.9.2

### ISSUE THREAD

**Issue by kuzmenkov111** [fstpackage/fst#213]
Hi! Many thanks for your work and great package!
What about update up to 0.9.2.? What is your expectation/plans? 

B.W. Alexey

**Comment by MarcusKlik** [comment]
Hi @kuzmenkov111,

thanks and I'm happy to read that `fst` works for you!

To answer your question, my plans are to

* publish the [syntheticbench](https://github.com/fstpackage/syntheticbench) package to CRAN. With this package `fst` can be thoroughly benchmarked against other serialization options (e.g. `feather` and `parquet`). It contains generators to create synthetic datasets of various distributions and types to pinpoint the strengths and weaknesses of the measured serializers. This package will also be important for further performance optimizations in `fst`.

* publish the [lazyvec](https://github.com/fstpackage/lazyvec) package. With this package, custom ALTREP vectors can be generated using only `R` code. It also contains a toolset for accessing ALTREP vector metadata and triggering ALTREP calls which are very useful when developing ALTREP implementations. Users can create new packages (with a dependency on `lazyvec`) that expose these custom vectors. Could be used to create virtual datasets from _fst_ files.

* create `python` bindings for `fst` and update the `fstlib` library with new types needed to facilitate python's `datatable` and `pandas` packages.

* update `R`'s `fst` package with the new `fstlib` API and release `0.9.2`

So much to do and so little time :-) I'm afraid it might be a few months before the next version of `fst` will be released!

thanks

**Comment by kuzmenkov111** [comment]
Extremely much to do... For me `fst ` package is a revolutionary package on par with `data.table` and `dplyr`

many thanks!!!

**Comment by MarcusKlik** [comment]
dunno about that but thanks for the compliment! :-)
