### ISSUE TITLE
ERROR: Error opening fst file for reading, please check access rights and file availability

### ISSUE THREAD

**Issue by Morais14** [fstpackage/fst#217]
When i try read a bunch of fst files in data folder of my shiny app i get the error:

> ERROR: Error opening fst file for reading, please check access rights and file availability

My code works fine without the shiny app and all files are loaded to the global enviroment:

```
temp1 = list.files(path = "data/", pattern = "*.fst")

list2env(lapply(setNames(temp1, make.names(
  gsub("*.fst$", "", temp1)
)),
read_fst), envir = .GlobalEnv)

```
Thanks @MarcusKlik

**Comment by MarcusKlik** [comment]
Hi @Morais14,

thanks for your question!
The error signals that the files can't be located which could mean that the shiny app is run:

* from a different _working directory_ which makes the relative file paths incorrect
* with different credentials (as a different user) and that user has no access to the file locations
* from a server and the files are located on a inaccessible network drive (firewalls)

Could any of these be the cause of your problem?

Deep down, the error is causes by a `ifstream::open()` call in the underlying `C++` library. That call requires only read access to the file locations. Perhaps you could add a bit of test code to verify the existence of the files, e.g. with `file.exists()`. You could also try to set some breakpoints in the application (if you're using `RStudio`) just before the call to `read_fst()` and see if that gives you more information.

Is there any information in the _~/ShinyApps/log/_ directory that could be of use?

Hope these pointers can offer you some help!

**Comment by Morais14** [comment]
Hi @MarcusKlik !
Thanks for your reply!
I use the same code for the function readRDS and works fine. See below:

```
pathit <- function(FUN, path) {
  function(file, ...) {
    FUN(file = file.path(path, file), ...)
  }
}
readRDS2 <- pathit(readRDS, "data/")
temp = list.files(path = "data/", pattern = "*.rds")
list2env(lapply(setNames(temp, make.names(
  gsub("*.rds$", "", temp)
)),
readRDS2), envir = .GlobalEnv)

```
For that reason i suspect that error seems to be caused for something related to the read_fst function. My apologies for don't reported this firstly.

I'm running the app in local Rstudio in Windows. When all my files are rds format the app works fine. But if i save them in fst format the error appears.

Many thanks again!

**Comment by MarcusKlik** [comment]
Hi @Morais14, that's very strange. You just switch the `read_fst/write_fst` for `readRDS/saveRDS` and then suddenly it throws the error?

Would there be a chance to post a link to the Shiny application's code or perhaps a comparable (simple) one with the same structure and some _fst_ files in the data folder?

thanks!

**Comment by Morais14** [comment]
Hi @MarcusKlik , i add an attachment. In this attachment i put two app's. One read all rds files in data folder, and other read all fst files in data folder (but the error occurs).

Many thanks for all your attention!

[rds_fst.zip](https://github.com/fstpackage/fst/files/3762548/rds_fst.zip)

**Comment by MarcusKlik** [comment]
Hi @Morais14, I fixed your App, there was a problem with relative paths and encoding (which you probably didn't have :-)). Here's the corrected Application, I've added a git repository for you to view the diffs.

[rds_fst.zip](https://github.com/fstpackage/fst/files/3771632/rds_fst.zip)

hope that helps!

**Comment by Morais14** [comment]
Hi @MarcusKlik !

Many Thanks!

**Comment by RPanczak** [comment]
Dear @MarcusKlik 
Could you please elaborate on what exactly was the problem with relative paths here?
We run into the same error message. It's hard to produce repex because code runs on one machine and fails on the other 🤯 but maybe with a hint from you I could track it down.
Thanks in advance!
