### ISSUE TITLE
Forward ellipsis in str.fst_table()

### ISSUE THREAD

**Issue by nbenn** [fstpackage/fst#219]
Is there a reason why `...` in `str.fst_table()` is not forwarded? I'd expect something like

```r
str.fst_table <- function(object, ...) {
  str(unclass(object), ...)
}
```

at

https://github.com/fstpackage/fst/blob/7713413d24fa44d6891abb25ec7a6fc17cd90fa7/R/fst_table.R#L175-L177

This would then allow for things like `max.level` to be obeyed by `str.fst_table()`, no?

**Comment by MarcusKlik** [comment]
Hi @nbenn, thanks for reporting!

The ellipsis is now forwarded in the `str()` generic, well spotted!
