### ISSUE TITLE
Problem with dates

### ISSUE THREAD

**Issue by derekholmes** [fstpackage/fst#22]
fst is not respecting dates.. I hope that is an easy fix

```
> u1=data.frame(DT=Sys.Date()-1:10,variable=rep(c("A","B"),5), value=1:10)
> write.fst(u1,"c:\\t\\u1.fst")
> u1
           DT variable value
1  2017-02-05        A     1
2  2017-02-04        B     2
3  2017-02-03        A     3
4  2017-02-02        B     4
5  2017-02-01        A     5
6  2017-01-31        B     6
7  2017-01-30        A     7
8  2017-01-29        B     8
9  2017-01-28        A     9
10 2017-01-27        B    10
> u2=read.fst("c:\\t\\u1.fst")
> u2
      DT variable value
1  17202        A     1
2  17201        B     2
3  17200        A     3
4  17199        B     4
5  17198        A     5
6  17197        B     6
7  17196        A     7
8  17195        B     8
9  17194        A     9
10 17193        B    10
> 
```

**Comment by MarcusKlik** [comment]
Thanks for pointing that out. Indeed a `Date` value is just a double with class 'Date'. The same is true for a `POSIXct` type, which is also not respected by `fst` I see. Will fix as soon as possible!

**Comment by MarcusKlik** [comment]
Hi @derekholmes, the `Date` type should now be respected and your code example is added as a test in the package. I'm converting `Date` types which have a `double` type as base to `integer` internally as can be seen in [the test](https://github.com/fstpackage/fst/blob/develop/tests/testthat/test.date.R#L15-L19). This gives much better performance and higher compression ratio's (double's are very hard to compress effectively).

Thanks again for reporting the issue!
