### ISSUE TITLE
FSTConfiguration got a recursion init

### ISSUE THREAD

**Issue by pli2014** [fstpackage/fst#224]
org.nustaq.serialization.FSTConfiguration#createConfiguration(org.nustaq.serialization.FSTConfiguration.ConfType, boolean)

```
    public static FSTConfiguration createConfiguration(ConfType ct, boolean shareRefs) {
        return createConfiguration(ct,shareRefs);
    }
```
    <groupId>de.ruedigermoeller</groupId>
    <artifactId>fst</artifactId>
    <version>2.55</version>

**Comment by MarcusKlik** [comment]
Hi @pli2014, thanks for reaching out, I was a bit puzzled with your issue but believe you are referring to [this code](https://github.com/RuedigerMoeller/fast-serialization/blob/59f8f800b79479d0b9c80901cf55903d9b027f26/src/main/java/org/nustaq/serialization/FSTConfiguration.java#L423-L425) ?

That's in the [_fast-serialization_](https://github.com/RuedigerMoeller/fast-serialization) library for Java JDK serialization, another serialization library unrelated to this one!

Best file your issue there :-)
