### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by waynelapierre** [fstpackage/fst#247]
I have used your fst package for a while and it works great. I currently save my datasets in csv format but I am considering fst format as a substitute. I would like to know whether backward compatibility will be guaranteed for future releases of your fst package because I don't want to risk not being able to access my datasets when there is a breaking change.

**Comment by renkun-ken** [comment]
In the README

>Note to users: From CRAN release v0.8.0, the fst format is stable and backwards compatible. That means that all fst files generated with package v0.8.0 or later can be read by future versions of the package.

I’ve been using fst in work and production for a long time. It’s stability and backward compatibility are quite impressive.

**Comment by waynelapierre** [comment]
Based on the number of contributors to this package, I tend to consider it as a one-person hobby project. I would like to know how long-term this package will be maintained.

**Comment by MarcusKlik** [comment]
Hi @waynelapierre, thanks for your question.

As @renkun-ken already indicates, all future `fst` releases will be able to read previous versions (>0.8.0) of _fst_ files.

But you're right to ask about long-term maintenance. Currently, there are only few authors of the _fst_ package and I'm the sole author of the (C++) `fstlib` library on which the package is based. Although that may change in the future, I understand your question given the current setup.

But note that even if the `fst` package would be discontinued, you will always be able to read your stored files using the latest published version, so you're data is 'safe' in that regard...

thanks
