### ISSUE TITLE
Some Benchmark Feedback

### ISSUE THREAD

**Issue by phillc73** [fstpackage/fst#25]
Not sure where else to leave this, but wanted to provide some benchmark feedback.

My data isn't huge, but it does need to be loaded into a Shiny app, so every millisecond counts. The data is also periodically transferred from a remote server to shinyapps.io, where the app is hosted, so file size is also a concern.

```r
pryr::object_size(fbHistoricResultsSQL)

> 143 MB
```

Writing the object to the files:

```r
microbenchmark(times=10,
write.csv(fbHistoricResultsSQL, "fbHistoricResultsSQL.csv"),
data.table::fwrite(fbHistoricResultsSQL, "fbHistoricResultsSQL_fwrite.csv"),
saveRDS(fbHistoricResultsSQL, "fbHistoricResultsSQL.Rds"),
feather::write_feather(fbHistoricResultsSQL, "fbHistoricResultsSQL.feather"),
fst::write.fst(fbHistoricResultsSQL, "fbHistoricResultsSQL.fst"),
fst::write.fst(fbHistoricResultsSQL, "fbHistoricResultsSQL_compressed.fst", compress = 100)
)
```

`Rds` is left at default compression settings.

Speed to write isn't a huge concern for me, as it's done on a remote server controlled by a cron job. `fst` is fastest, while `fst` with 100 compression is still quicker than `Rds`, but slower than `feather` and `fwrite`.

```r
Unit: milliseconds
                                                                                             expr        min         lq       mean     median         uq       max neval
                                      write.csv(fbHistoricResultsSQL, "fbHistoricResultsSQL.csv") 43327.6840 44443.1966 51946.9457 51962.6121 58955.6631 62506.981    10
                      data.table::fwrite(fbHistoricResultsSQL, "fbHistoricResultsSQL_fwrite.csv")   499.8059   517.6073   643.5355   525.9915   672.7274  1077.391    10
                                        saveRDS(fbHistoricResultsSQL, "fbHistoricResultsSQL.Rds") 11399.7927 13771.2299 17093.8948 18078.2103 20357.4133 20481.531    10
                     feather::write_feather(fbHistoricResultsSQL, "fbHistoricResultsSQL.feather")   354.8188   416.0689   632.8047   505.7227   878.3790  1132.388    10
                                 fst::write.fst(fbHistoricResultsSQL, "fbHistoricResultsSQL.fst")   340.8930   362.4958   591.8688   418.2773  1050.4093  1059.357    10
 fst::write.fst(fbHistoricResultsSQL, "fbHistoricResultsSQL_compressed.fst",      compress = 100)  1655.4058  2262.0219  3968.6550  4650.9530  4881.5290  6272.078    10
```
`Rds` does create the smallest file sizes, with 100 compressed `fst` a little way behind.
```r
> file.size("fbHistoricResultsSQL.csv")
[1] 114849990
> file.size("fbHistoricResultsSQL_fwrite.csv")
[1] 90092546
> file.size("fbHistoricResultsSQL.Rds")
[1] 26563307
> file.size("fbHistoricResultsSQL.feather")
[1] 148798120
> file.size("fbHistoricResultsSQL.fst")
[1] 148459382
> file.size("fbHistoricResultsSQL_compressed.fst")
[1] 34119811
```
For ease of viewing, the `Rds` file is about 25.3MB and the 100 compressed `fst` is 32.5MB.

Now, reading the data back in from the saved files:

```r
microbenchmark(times=10,
csv <- read.csv("fbHistoricResultsSQL.csv", sep=",", stringsAsFactors = FALSE),
fread_csv <- fread("fbHistoricResultsSQL_fwrite.csv"),
Rds_in <- readRDS("fbHistoricResultsSQL.Rds"),
feather_in <- feather::read_feather("fbHistoricResultsSQL.feather"),
fst_in <- fst::read.fst("fbHistoricResultsSQL.fst"),
fst_compressed_in <- fst::read.fst("fbHistoricResultsSQL_compressed.fst")
)
```

`fst` wins again, but crucially, 100 compressed `fst` is significantly faster than `Rds`.

```r
Unit: milliseconds
                                                                             expr        min         lq       mean     median        uq       max neval
 csv <- read.csv("fbHistoricResultsSQL.csv", sep = ",", stringsAsFactors = FALSE) 17274.9592 18683.0098 20032.4658 19753.4444 21068.422 23651.957    10
                            fread_csv <- fread("fbHistoricResultsSQL_fwrite.csv")  2784.1564  3508.4621  3729.2320  3723.2384  4078.078  4672.571    10
                                    Rds_in <- readRDS("fbHistoricResultsSQL.Rds")  3381.8752  5061.3580  5383.2858  5359.9506  5845.889  6525.150    10
              feather_in <- feather::read_feather("fbHistoricResultsSQL.feather")   356.4536   437.6393   821.1549   741.2754  1121.273  1700.306    10
                              fst_in <- fst::read.fst("fbHistoricResultsSQL.fst")   355.2809   363.5862   712.1544   594.1401  1088.736  1438.211    10
        fst_compressed_in <- fst::read.fst("fbHistoricResultsSQL_compressed.fst")   667.0044   853.3418  1357.8370  1489.1858  1627.346  1957.504    10
```

For my use case, which is a combination of desiring small binary file size and fastest read time, the 100 compressed `fst` looks to be just about the right job.

Of course any advances in compression to bring the 100 compressed `fst` below the `Rds` file size, without dramatic read speed impact, would be fantastic.

**Comment by MarcusKlik** [comment]
Thanks a lot for an interesting set of benchmarks! Good to see that `fst` using maximum compression settings works for you at the moment. I still have a lot of optimizations planned to increase the compression performance:

- multi-threaded compression and decompression and disk IO on a separate thread (issue #3)
- use of SSE2 extensions to speed-up the binary filters used in `fst`  (issue #1)
- using brotli or ZSTD (with a trained dictionary) to speed-up text compression (issue #21)
- further optimization of the type-specific compressors used in `fst` (for example on-the-fly factorization of character vectors)
- a 'high-compression' setting specifically designed for network IO (using larger chunks and more (slower) compression (issue #23)
- selection of the optimal stack-buffer size used internally by `fst` (currently 16 kB).

To monitor the effects of these enhancements from version to version, it might be a good idea to compose a set of data sets to benchmark each `fst` package version. What kind of data did you use in your benchmarks?

**Comment by phillc73** [comment]
Looks like a lot of great enhancements planned!

I should have stated some more information about my data set in the original post.

The data set was 956400 rows across 21 columns. A mixture of character strings, integers and floats. There was also a Date column, which I need to check after subsequently seeing Issue #22. In short, the data is a collection of historic horse rating data.

I could post the column type breakdown later.

**Comment by MarcusKlik** [comment]
Thanks @phillc73 , it would be interesting to see the column breakdown. If your data is public, I could also include it in the corpus of data sets to use for the benchmark ?

**Comment by phillc73** [comment]
@MarcusKlik Here is the column info:

```r
> str(fbHistoricResultsSQL)
'data.frame':	959638 obs. of  21 variables:
 $ DATE     : chr  "2014-01-01" "2014-01-01" "2014-01-01" "2014-01-01" ...
 $ TIME     : chr  "1200" "1200" "1200" "1200" ...
 $ BFOddsWin: num  13.7 23 94.6 63 534.1 ...
 $ COURSE   : chr  "Tramore" "Tramore" "Tramore" "Tramore" ...
 $ POS      : chr  "P" "4" "7" "6" ...
 $ HORSE    : chr  "Popmurphy" "Bawntameena" "Claire Pet" "Detank" ...
 $ STAT     : chr  "" "" "" "" ...
 $ FBRr     : int  4 9 11 13 6 7 11 2 14 1 ...
 $ tjortpct : num  7.41 0 NA NA 0 NA 5.88 0 12 20 ...
 $ tcortpct : num  0 0 0 33.3 0 ...
 $ jcortpct : num  16.07 7.14 14.29 NA 7.41 ...
 $ DIMove   : int  -4 0 NA NA 0 0 0 0 NA 0 ...
 $ bfwinr   : int  4 6 9 8 12 5 14 13 10 1 ...
 $ ORr      : int  3 8 3 8 8 1 8 8 7 5 ...
 $ RUNNERS  : chr  "14" "14" "14" "14" ...
 $ thcpct   : num  6.52 2.6 0 1.49 4.44 ...
 $ tclpct   : num  4.71 1.94 4.26 2.56 5.86 ...
 $ FBR V%   : num  -0.04 0.27 2.22 0.26 33.06 ...
 $ COMr     : int  9 8 11 14 5 11 7 9 5 1 ...
 $ rta2     : chr  "Maiden" "Maiden" "Maiden" "Maiden" ...
 $ TRr      : int  11 10 13 9 7 12 3 8 5 2 ...
```
The Date column is stored in the database as character and converted later. I'll just need to be careful about where I do that, and make sure it's in the app after the `fst` file has been read in.

Unfortunately, the data isn't public. The best I could do would be an extract of maybe 100 rows, but sadly I can't publicly share the whole lot.

**Comment by MarcusKlik** [comment]
Thanks a lot for that! And the 'Date issue' will be fixed in the next version of `fst`, forgot to write the class name attribute there :-).

**Comment by MarcusKlik** [comment]
Closing this issue, thanx @phillc73 for the benchmarks and `Date` attribute will be serialized in next version of `fst`
