### ISSUE TITLE
fst detects (and says it's using) 32 threads, but appears to only use 1

### ISSUE THREAD

**Issue by coussens** [fstpackage/fst#252]
First off, fst is awesome! Thanks for all your hard work.

I'm labelling this a question, since I'm pretty sure the problem is on my end, and not with fst (because I'm not having this problem on all machines, just this CentOS machine I'm currently working on) but wanted to see if this is a common issue and if anyone has a suggestion as to why this might be occurring. 

Basically, when reading an .fst file, I can check the CPU utilization and see that only one thread is being used, even though it seems like fst knows that 32 are available:

> library(fst)
> fst package v0.9.4
> (OpenMP detected, using 32 threads)

> > threads_fst()
> [1] 32

**Comment by MarcusKlik** [comment]
Hi @coussens, thanks, I'm glad `fst` works for you!

About your issue, because `fst` detects the 32 threads on your system, it seems very likely that `OpenMP` is installed correctly. But `fst` can switch back to single core mode after a fork has been detected. Are you running `fst` in multiple processes or are you using one of the parallel (cluster) methods to execute your code (like `clusterApply()`) ?

thanx

**Comment by coussens** [comment]
Thanks, @MarcusKlik. I'm pretty sure this was the issue. I suspect what was happening is that I had some zombie R processes lying around from previously using disk.frame (and likely improperly terminating it at some point). After doing a `killall R`, it seems like .fst is now using multiple threads again! 

Relatedly, do you know if there are any helper functions or options one could use from inside R/RStudio that would allow one to check for and/or eliminate any unwanted forks?

**Comment by MarcusKlik** [comment]
Hi @coussens, I've added a diagnostic method `is_forked()` to the `fstcore` package (currently on the _release_ branch) that will tell you if the current process has been forked, so now you can do:

``` r
library(parallel)

# helper
detect_fork <- function(node) {
  fstcore:::is_forked()
}

# no fork yet
detect_fork()
#> [1] FALSE

# create a cluster
cluster <- makeForkCluster(2)

# detect fork status of each node
parLapply(cluster, 1:2, detect_fork)
#> [[1]]
#> [1] TRUE
#> 
#> [[2]]
#> [1] TRUE

# stop the cluster
stopCluster(cluster)
```

(note that this will only work on _linux-alikes_ as forking has no meaning on `Windows` systems)

This method will detect a fork for you. But I'm not sure how you could delete a forked process automatically from `R`. From the command line you can use `ps -a` to search for the `R` session and then use `pgrep -P [rsession_id]` to recursively find child processes for that session, perhaps you could use that to find and eliminate your unwanted processes?

Thanks for your question and I would be interested to know if the `is_forked()` method helps you with your use case!

**Comment by coussens** [comment]
@MarcusKlik Sorry for the delayed response. Thanks for this! I think it's definitely helpful to have an easy way to check this when troubleshooting performance issues.

**Comment by fstpackage** [comment]
Hi @coussens, no worries and thanks for your response! Is the new diagnostic method enough for your purposes so that we can close the issue?

**Comment by coussens** [comment]
Woops. Meant to close it already. Just did it now.
