### ISSUE TITLE
fst 0.9.4 package load fails with Rcpp 1.0.6 in R 4.1.0 (but not in R 4.0.5 or with Rcpp 1.0.7)

### ISSUE THREAD

**Issue by twest820** [fstpackage/fst#262]
On the surface, it appears fst is in compatible with R 4.1 installs using Rcpp 1.0.6. Curiously, though, I have one machine that's somewhat behind on updates with R 4.0.5 and Rcpp 1.0.6. fst 0.9.4 loads fine there, so the error message above might not be entirely correct.
```R
> library(fst)
Error: package or namespace load failed for ‘fst’:
 .onLoad failed in loadNamespace() for 'fst', details:
  call: setnrofthreads(nr_of_threads)
  error: function 'Rcpp_precious_remove' not provided by package 'Rcpp'
```

I was able to get around this by updating the R 4.1 machine to Rcpp 1.0.7 but figured it might be worth capturing this as a known issue.

**Comment by MarcusKlik** [comment]
Hi @twest820, because updating the machine solved your problem, I would like to close this issue, thanks for reporting!
