### ISSUE TITLE
Binaries through r-universe

### ISSUE THREAD

**Issue by SebKrantz** [fstpackage/fst#268]
In case this is of interest, I have set up a [fastverse r-universe](https://fastverse.r-universe.dev/) that builds binary versions of the GitHub version of your package for MAC and Windows (new binaries are built within an hour of a new commit to your repo). Users can install these binaries using: 

```
# Enable repository from fastverse
options(repos = c(
    ropensci = 'https://fastverse.r-universe.dev',
    CRAN = 'https://cloud.r-project.org'))

# Download and install fst in R
install.packages('fst')

# Or simply: 
install.packages('fst', repos = c(ropensci = 'https://fastverse.r-universe.dev', 
                                  CRAN = 'https://cloud.r-project.org')) # Needed for dependencies
```

You can also add a Badge to your README.md:

[![fst status badge](https://fastverse.r-universe.dev/badges/fst)](https://fastverse.r-universe.dev)

**Comment by MarcusKlik** [comment]
Hi @SebKrantz, that's great, I'll add the banner to the README file, thanks a lot!
