### ISSUE TITLE
Can't write to home (~/) directory

### ISSUE THREAD

**Issue by PoGibas** [fstpackage/fst#41]
I can't save `fst` to home directory when using `~/` instead of full path.

```
library(fst)
# Save file to home directory - works
write.fst(mtcars, "/home/USER/dummy.fst")
# Save file to home directory - produces error
write.fst(mtcars, "~/dummy.fst")
```
Error:
```
Error in fstStore(path, x, as.integer(compress)) : 
  There was an error creating the file. Please check for a correct filename.
```

On the other hand, both `read.fst(mtcars, "~/dummy.fst")` and `read.fst(mtcars, "/home/USER/dummy.fst")` work fine.

Session info:

```
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] fst_0.7.2      memuse_3.0-2

loaded via a namespace (and not attached):
[1] clisymbols_1.1.0  tools_3.3.2       Rcpp_0.12.10      data.table_1.10.4
```

**Comment by MarcusKlik** [comment]
Hi @PoGibas , thanks for submitting your issue! I fixed this by applying `normalizePath` to parameter `path` before writing to file. This was done already in `read.fst` but not in `write.fst`, hence your problem. Should be fixed now!

**Comment by ryankennedyio** [comment]
Hey @MarcusKlik , just wondering if this fix was pushed to CRAN, or only github's development branch? Still getting this issue on some fresh installations.

**Comment by MarcusKlik** [comment]
Hi @ryankennedyio , it's not yet pushed to CRAN, the next `fst` release is due around June. Apologies for the inconvenience!

**Comment by ryankennedyio** [comment]
No problem, thanks for the update! Great work on this package.

**Comment by MarcusKlik** [comment]
Hi @ryankennedyio , thanks! The plan is to have shorter intervals between CRAN releases after June. But in the coming release I try to accommodate as many format changes as possible (e.g. attributes, row-binding, column-binding, hashes, list columns, etc) so that subsequent releases will be backwards compatible. Once the format is stable, the release cycle can be much shorter...
