### ISSUE TITLE
The option columns doesn't seem to work.

### ISSUE THREAD

**Issue by juanpide** [fstpackage/fst#43]
No matter what I choose the option column doesn't seem to work.
`myDT <- read.fst("myfile.fst",  columns = "firstcol",as.data.table = TRUE)
`
It says

> Error in fstRead(fileName, columns, from, to) : 
>  Selected column not found.

But I know it exist.
Using a vector of names doesn't work either.

But if I just use it without any column option it works well

> myDT <- read.fst("myfile.fst" ,as.data.table = TRUE)

**Comment by juanpide** [comment]
I'm sorry, it was a problem with my R.

**Comment by MarcusKlik** [comment]
Thanks for submitting your issue and good that your problem was solved!
