### ISSUE TITLE
Feature request: Routines to get meta data of the data frame without opening the whole data

### ISSUE THREAD

**Issue by wei-wu-nyc** [fstpackage/fst#45]
I don't know if this is requested. It would be helpful to provide functions that gives back some basic info about the data frame in the save fst file without opening the whole file. For example:
1. Number of columns and rows. So that the users can determine whether to open the whole file or read part of the file.
2. May be give the name of the columns and the data type of each columns.

Thanks.

**Comment by MarcusKlik** [comment]
Hi @wei-wu-nyc , thanks for your request. The latest CRAN release of the `fst` package actually has a method `fst.metadata` which shows some basic information about a `fst` file in `tibble`-style (such as names and types). Future releases will show more information, for example the key columns and dimensions of the stored table. Hope this helps!

**Comment by wei-wu-nyc** [comment]
Thanks @MarcusKlik, this actually is enough for my current need. Did not see the fst.metadata call.

**Comment by MarcusKlik** [comment]
Using method `fst.metadata` from the _develop_ branch of `fst`:

```r
x = data.table(X = 1:10, B = LETTERS[1:10], key = "X")
write.fst(x, "1.fst")
fst.metadata("1.fst")
```

 will now give you output like:

```r
<fst file>
10 rows, 2 columns (1.fst)

* 'X': integer (key 1)
* 'B': character
```
