### ISSUE TITLE
Saving empty data.table throw an error and created a file that is malformed

### ISSUE THREAD

**Issue by wei-wu-nyc** [fstpackage/fst#47]
When trying to save a data.frame with 0 row.  fst R package throw an error with error message:
Error in fstStore(normalizePath(path, mustWork = FALSE), x, as.integer(compress)) :
  The dataset contains no data.
And the resulted .fst file is malformed. read.fst() report the file format is not recognized.

1. May be fst should allow saving an empty data.table or data.frame? R default save function can save an empty data.frame.
2. Even if you don't allow saving of an empty data frame, the error handling could be more careful. May be should not throw an error? Should clean up the failed save and either close the file with proper format or delete the file.

**Comment by MarcusKlik** [comment]
Hi @wei-wu-nyc , thanks for reporting that. Perhaps I should allow empty data sets. In that case only meta data is stored (column names, keys and possible attributes), similar to a 0-row `data.frame`. `fst` will also get a `fst-object` (next version) that can be used to access a `fst` file like a `data.frame`, so it would be better to have 0-row functionality, like in `data.table`. I'll add your request as a feature, thanks!

**Comment by MarcusKlik** [comment]
Hi @wei-wu-nyc, writing an empty data set to file now generates the following errors:

``` r
# Completely empty
fst::fstwrite(data.frame(), "empty.fst")
#> Error in fststore(normalizePath(path, mustWork = FALSE), x, as.integer(compress), : Your dataset needs at least one column.

# No rows
fst::fstwrite(data.frame(X = integer()), "empty.fst")
#> Error in fststore(normalizePath(path, mustWork = FALSE), x, as.integer(compress), : The dataset contains no data.
```

The column- and row checks are now done before opening the actual `fst` file, so no malformed file is created now when an empty table is used.

That only partly implements your request, because the feature to store tables without rows (only column metadata) is not implemented yet, but I will get to that later!

**Comment by wei-wu-nyc** [comment]
Thanks Mark.

**Comment by MarcusKlik** [comment]
Hi @wei-wu-nyc, your request to be able to store empty tables (but with metadata) is planned for `fst` version v0.8.6 in #99.

Thanks again for your feature request!
