### ISSUE TITLE
Make data.table an optional dependency

### ISSUE THREAD

**Issue by jimhester** [fstpackage/fst#54]
This would lighten the cost of using **fst** on CI systems, if **data.table** output is not used for a given package.

**Comment by MarcusKlik** [comment]
Hi @jimhester , thanks for taking a close look at `fst` and love your work by the way (can't live without `devtools`), thanks for that!

I can make `data.table` optional for `fst` as it is now. But at future milestones, I will probably need more methods from the `data.table` package as more functionality is added to the package. For example, when (on-the-fly) grouping functionality is added, I will use `data.table`'s grouping methods to perform chunk-wise groupings. Also, I plan to use the fast radial sort algorithm of `data.table` to do the in-memory sorting during the merge-sort algorithm planned for [milestone ](https://github.com/fstpackage/fst/issues/48)_advanced operations_. At that point, the dependency on `data.table` is probably not optional anymore.

Another planned feature is converting a `csv` file directly to a `fst` file with a very small memory footprint. That requires the multi-threaded `fread` method from `data.table` as well.

So I will make the dependency optional for now, but can't make any promises for the future :-)

**Comment by MarcusKlik** [comment]
Package `data.table` is an [optional dependency](https://github.com/fstpackage/fst/blob/develop/DESCRIPTION#L15) now, thanks @jimhester for the recommendation!
