### ISSUE TITLE
Provide alternative function aliases

### ISSUE THREAD

**Issue by jimhester** [fstpackage/fst#55]
`foo.bar` naming convention is less than ideal as it is ambiguous if the function is a simple one or a S3 method for `foo`. This is compounded by the fst package defining objects of class `fst.metadata`, which results in a function named `print.fst.metadata` that could be either a print method for `fst.metadata` objects, a `print.fst` method for `metadata` objects or a `print.fst.metadata` function, with no way of knowing which based on the function name.

Please consider adding unambiguous aliases, `read_fst()`, `readFst()` etc. and ideally consider changing the name of your S3 class to avoid confusion.

**Comment by statquant** [comment]
It looks like some packages define some aliases func_name and funcName for all functions. This is a nice thought for their users, we all have out preferences...

**Comment by jimhester** [comment]
Yes, https://github.com/mllg/checkmate is a good example that defines both camel case and snake case functions.

**Comment by MarcusKlik** [comment]
Hi @jimhester , thanks for your feedback! You're right off course, using the `foo.bar` convention is ambiguous to S3 methods and the `foo_bar()` and `fooBar()` aliases don't have this problem. But I'm always confused that [Google's R Style guide](https://google.github.io/styleguide/Rguide.xml#identifiers) explicitly states:

```
FunctionName 
GOOD: CalculateAvgClicks 
BAD: calculate_avg_clicks , calculateAvgClicks 
```

Would you recomment the [tidyverse style guide](http://style.tidyverse.org/functions.html#naming) as the definitive guide for packages?

@statquant: perhaps adding multiple aliases would be a solution but might also give the impression that the two aliases are in fact two different methods in the package.

The reason to go for `write.fst` and `read.fst` was a very practical one; to offer the user functions similar to the very familiar `write.csv`, `write.table` etc. In RStudio:

![image](https://cloud.githubusercontent.com/assets/24658401/25500522/a0cf21ca-2b8f-11e7-8f78-ec5710184816.png)

But the `fooBar()` convention is also used in base-R (`foo_bar()` not so much):

![image](https://cloud.githubusercontent.com/assets/24658401/25500727/6cfb668c-2b90-11e7-9cf3-ac309e8fada9.png)

And the `feather` package uses `read_feather` and `write_feather` (tidyverse style obviously :-)).

There's a lot of different styles out there! Personally I don't have a strong preference as long as the package as a whole is consistent with a single style.

**Comment by jimhester** [comment]
I think google's style guide is just wrong on this point, in general naming convention is largely a matter of preference but using dots in particular have real ambiguity problems as mentioned above. I personally do follow the tidyverse style, but for the most part consistency within a given style is the most important thing.

I think providing aliases is fine actually as long as they are both documented in the same place.

**Comment by MarcusKlik** [comment]
Great, I will provide aliases for `read.fst` and `write.fst` and use the tidyverse style for future methods. Thanks a lot!

**Comment by MarcusKlik** [comment]
The latest develop build of `fst` has aliases now for the package's main methods. I also added a [unit test ](/fstpackage/fst/blob/develop/tests/testthat/test.lintr.R) that runs almost all of @jimhester's `linters` on the package code and unit tests. A few `linters` have been disabled and the list of file names is manually set to avoid unexpected results (the `RcppExports.R` file is not correctly excluded for example ).

Thanks @jimhester for your package `lintr`, happy to use it!
