### ISSUE TITLE
Error/crash when saving factor column with 0 factor levels

### ISSUE THREAD

**Issue by martinblostein** [fstpackage/fst#56]
For me `write.fst` either raises an error or crashes when fed a data.frame with a factor column with zero levels. Such a vector occurs when a factor vector is initialized with only NA values.

Here is a small example:
```
df <- data.frame(A = 1:3, B = as.factor(c(NA, NA, NA)))
fst::write.fst(df, "dt.fst")
```
The CRAN version of `fst` unpredictably either raises this error within R:
```
Error in fstStore(path, x, as.integer(compress)) : 
  LENGTH or similar applied to pairlist object
```
or cases a fatal error and kills the R session (I believe this occurs because uncaught error comes up in C++ code.) Using the dev version of `fst`, the behaviour is the same except the error reads:
```
Error in fstStore(normalizePath(path, mustWork = FALSE), x, as.integer(compress),  : 
  LENGTH or similar applied to environment object
```

I am using R version 3.3.3 on Windows 7, 64 bit.

**Comment by MarcusKlik** [comment]
Hi @martinblostein , thanks for reporting the error! Indeed, there is currently no check on writing a zero-length character vector [(this code needs a check)](https://github.com/fstpackage/fst/blob/develop/src/fstcore/character/character_v6.cpp#L122).

Will fix as soon as possible!

**Comment by MarcusKlik** [comment]
This issue is fixed by detecting a zero-length level attribute on the factor. An added bonus is that when there is a zero-length level vector, values can only be `NA`, so there is no need to store the values separately. For those case, long factor columns can be compressed into a few bytes:

```r
# Sample dataset with 'NA' factor column
dt <- data.table(A = factor(rep(NA, 2000000)))
object.size(dt)  # 8 MB

write.fst(dt, "factor_column.fst")
file.size("factor_column.fst")  # 255 bytes

x <- read.fst("factor_column.fst")
object.size(x)  # 8 MB back again
```

So the on-disk size is only 255 bytes, while the vector is 8 MB :-)
