### ISSUE TITLE
Quick way to get file properties with read.fst

### ISSUE THREAD

**Issue by juanpide** [fstpackage/fst#58]
It would be great to have a quick way to get information from the fst files by using read.fst but without needing to read it completely.

I mean things such as:
Number of rows.
Number of columns.
Variable names.
Classes of that variables.

I guess they could be retrieved from the "metadata" of the file.
That could be important when working with large files.

**Comment by wei-wu-nyc** [comment]
fst.metadata() function.
See issue #45 https://github.com/fstpackage/fst/issues/45

**Comment by MarcusKlik** [comment]
Hi @skanskan, thanks for the request! As @wei-wu-nyc mentions, the `fst.metadata` method provides some information on the stored data set. With a stored data set like:

```r
nrOfRows <- 1000000
x <- data.table(
  Integer = 1:nrOfRows,  # integer
  Logical = sample(c(TRUE, FALSE, NA), nrOfRows, replace = TRUE),  # logical
  Factor = factor(sample(state.name, nrOfRows, replace = TRUE)),  # text
  Character = sample(state.name, nrOfRows, replace = TRUE),  # text
  Numerical = runif(nrOfRows, 0.0, 100),  # numericals
  stringsAsFactors = FALSE)

setkey(x, Logical, Character)
write.fst(x, "1.fst")
```

with the current `fst` CRAN release, you can retrieve some basic meta-data with:

```r
fst.metadata("1.fst")  # CRAN version

<fst file>
1e+06 rows, 5 columns (1.fst)

* 'Integer'  : integer
* 'Logical'  : logical
* 'Factor'   : factor
* 'Character': character
* 'Numerical': real
```

the `fst` latest _develop_ branch will also give you some information on (the order of) stored keys:

```r
fst.metadata("1.fst")  # latest dev

<fst file>
1000000 rows, 5 columns (1.fst)

* 'Integer'  : integer
* 'Logical'  : logical (key 1)
* 'Factor'   : factor
* 'Character': character (key 2)
* 'Numerical': double
```

The _class_ identifiers will be expanded with new types (e.g. `Date`, `integer64`) in next releases of `fst`.

For milestone '_interface_' (see #48), a more advanced interface is planned for accessing a `fst` file, With that interface you can access a on-disk `fst` file with a `data.frame` interface. Printing a small subset of the table will the be available from that interface (like `data.table`'s print functionality, where only the first and last couple of rows are shown).

Any extra ideas are very welcome!

**Comment by juanpide** [comment]
OK, thank you, that's what I was looking for.
