### ISSUE TITLE
Character encodings are not saved with file

### ISSUE THREAD

**Issue by adrianadermon** [fstpackage/fst#68]
I have found that when I write a data frame containing UTF-8 encoded characters, the encoding is lost when I read the file back into R. I am using R 3.4.0 (64-bit) and `fst` 0.7.2 on Windows 10.

Below is a minimal example illustrating the issue.

```r
library(fst)

# Create simple data frames containing non-english characters

# Default Latin-1 encoding
latin1 <- data.frame(x = "Ärende", stringsAsFactors = FALSE)

# UTF-8 encoding
utf8 <- data.frame(x = enc2utf8("Ärende"), stringsAsFactors = FALSE)

# Write fst files
write.fst(latin1, "test_latin1.fst")
write.fst(utf8, "test_utf8.fst")
# Write Rdata file
saveRDS(utf8, "test_utf8.Rdata")

# Read files
latin1_read <- read.fst("test_latin1.fst")
utf8_read <- read.fst("test_utf8.fst")
utf8_read_RDS <- readRDS("test_utf8.Rdata")
```

Printing to the console gives the following output:
```r
> print(latin1_read)
       x
1 Ärende
> print(utf8_read)
        x
1 Ã„rende
> print(utf8_read_RDS)
       x
1 Ärende
```
Notice that the output for the UTF-8 encoded file is wrong when written with `fst`, but not when written with RDS.

If we check the encodings of the data, we find that `fst` "forgot" the encodings when writing and reading, while RDS "remembered" it:
```r
> Encoding(latin1_read$x)
[1] "unknown"
> Encoding(utf8_read$x)
[1] "unknown"
> Encoding(utf8_read_RDS$x)
[1] "UTF-8"
```

This can be fixed by setting the correct encodings:
```r
# Set encodings on data read from fst
Encoding(latin1_read$x) <- "latin1"
Encoding(utf8_read$x) <- "UTF-8"
```
And now it works:
```r
> print(latin1_read)
       x
1 Ärende
> print(utf8_read)
       x
1 Ärende
```

It would be great if `fst` could retain this information. And thank you for your work - this package has hugely improved my workflow!

**Comment by MarcusKlik** [comment]
Hi @adrianadermon, thanks for submitting your issue and nice to hear that `fst` helps to improve your workflow!

Your code examples are very clear and informative. Indeed `fst` is not respecting the `UTF-8` encoding correctly at the moment and for many languages that might be a problem. At least `fst` should support `UTF-8`, but probably also `UTF-16` and `UTF-32`, `ASCII` and `Latin1` and perhaps more in the future. Also, retaining the encoding will be faster than converting all character columns to UTF-8 encoding (which I see package `feather` [is doing](https://github.com/wesm/feather/blob/master/R/src/feather-write.cpp#L244)). Such a conversion will definitely incur overhead, especially for byte-codes larger than 128.

Thanks, I will make sure the correct encoding is stored in a character column's metadata and put your issue up for the next CRAN release!

**Comment by MarcusKlik** [comment]
[It appears](https://github.com/hadley/r-internals/blob/master/strings.md#strings-charsxp) R only respects few encodings for character vector elements natively. The names of other encodings and which ones are available are platform-dependent. All R platforms support  `no encoding` for the current locale, `latin1` and `UTF-8` ([documented here](https://stat.ethz.ch/R-manual/R-devel/library/base/html/Encoding.html)). The R internals manual also [confirms](https://cran.r-project.org/doc/manuals/r-release/R-ints.html#Encodings-for-CHARSXPs) those findings.

So I guess the best strategy is to store encodings `none`, `latin-1` and `UTF-8` (for speed) and convert all other encodings to UTF-8. So that would incur only overhead for character columns other than the known formats.

Additional question is what would happen to a `fst` file written without encoding (the `none` variant) if opened on a different systems using a different 'locale'. However, the same question applies to a `saveRDS` / `readRDS` cycle, so we probably shouldn't worry too much about that:

``` r
empty1 <- data.frame(x = rep("Arende", 5), stringsAsFactors = FALSE)
saveRDS(empty1, "test_empty1.rds")
empty1_read <- readRDS("test_empty1.rds")
Encoding(empty1$x)
#> [1] "unknown" "unknown" "unknown" "unknown" "unknown"
Encoding(empty1_read$x)
#> [1] "unknown" "unknown" "unknown" "unknown" "unknown"
```

(`saveRDS` doesn't force an encoding as can be seen)

**Comment by MarcusKlik** [comment]
Hi @adrianadermon, `fst` is now retaining encoding information (in the latest develop version) as can be seen from the following script (based on your initial script):

```r
# create character columns with encoding
latin1 <- data.frame(x = "Ärende", stringsAsFactors = FALSE) # default latin1
utf8 <- data.frame(x = c(
  enc2utf8("Ärende"),
  "我能吞下玻璃而不傷身體。",
  "私はガラスを食べられます。それは私を傷つけません。"),
  stringsAsFactors = FALSE)  # UTF-8

Encoding(latin1$x)
#> [1] "latin1"

Encoding(utf8$x)
#> [1] "UTF-8" "UTF-8" "UTF-8"

# Write fst files
write.fst(latin1, "test_latin1.fst")
write.fst(utf8, "test_utf8.fst")

# Use R's internal serialization to compare
saveRDS(latin1, "test_latin1.rds")
saveRDS(utf8, "test_utf8.rds")

# Read files
latin1_read <- read.fst("test_latin1.fst")
utf8_read <- read.fst("test_utf8.fst")
latin1_read_rds <- readRDS("test_latin1.rds")
utf8_read_rds <- readRDS("test_utf8.rds")

# Encoding is retained
testthat::expect_equal(latin1_read, latin1_read_rds)  # passes
testthat::expect_equal(utf8_read, utf8_read_rds)  # passes

# Visual check
print(latin1_read$x)
#> [1] "Ärende"

print(utf8_read$x) 
#> [1] "Ärende"
#> [2] "我能吞下玻璃而不傷身體。"                          
#> [3] "私はガラスを食べられます。それは私を傷つけません。"
```

To maintain speed, `fst` assumes that the encoding of the first non-`NA` element of a character vector is identical to the encoding of the remaining column. In other words, `fst` assumes a vector that is uniformly encoded (like in the example above). But `fstwrite` has a new logical argument '_uniform.encoding_' that can be set to `FALSE` to check the encoding of each element separately (slower). More examples of using '_uniform.encoding_' that can be found in the [encoding unit tests](https://github.com/fstpackage/fst/blob/develop/tests/testthat/test.encoding.R).

I would be very interested to see if `fst` works correctly now on your locale!

(if you would like to test, please make sure that you use the latest develop version of `fst`):

```r
devtools::install_github("fstPackage/fst", ref = "develop")
```

**Comment by adrianadermon** [comment]
@MarcusKlik I don't know if this is still useful (I've been travelling and unable to test this before now), but this works perfectly. Thanks again for the great work!

**Comment by MarcusKlik** [comment]
Hi @adrianadermon, very useful indeed, thanks for testing! Do you think that the assumption of a uniformly encoded vector is a reasonable one in your experience or did you encounter many character vectors with mixed encodings?

**Comment by adrianadermon** [comment]
@MarcusKlik yes, that seems reasonable to me. I can't think of any situations where I would need mixed encodings in a vector - and if you run into such data, it should always be possible to re-encode it into pure utf8 before saving, right?

**Comment by MarcusKlik** [comment]
Hi @adrianadermon, exactly true! If you know that you have a mixed vector you can re-encode it yourself. And if you are not sure if the vector is uniformly encoded, parameter _uniform.encoding_ can be set to FALSE and `fst` will perform additional checks (will be slower though).

Thanks again for reporting!
