### ISSUE TITLE
fst doesn't appear to preserve ordered attribute of factors

### ISSUE THREAD

**Issue by eipi10** [fstpackage/fst#76]
Here's an example, using the development version of `fst` (version 0.7.3, installed on August 1, 2017):

```
dat = data.frame(x = ordered(c(LETTERS[c(1,1,2,4,1,3,4,3)])))
write.fst(dat, "test.fst", compress=100)
dat.fst = read.fst("test.fst")

str(dat)
```

> 'data.frame':	8 obs. of  1 variable:
> $ x: Ord.factor w/ 4 levels "A"<"B"<"C"<"D": 1 1 2 4 1 3 4 3

`str(dat.fst)`

> 'data.frame':	8 obs. of  1 variable:
> $ x: Factor w/ 4 levels "A","B","C","D": 1 1 2 4 1 3 4 3

`sessionInfo()`

> R version 3.4.1 (2017-06-30)
> Platform: x86_64-apple-darwin15.6.0 (64-bit)
> Running under: macOS Sierra 10.12.5
> 
> Matrix products: default
> BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib
> 
> locale:
>   [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
>   [1] grid      tools     stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>   [1] purrr_0.2.2.2      tidyr_0.6.3        tibble_1.3.3       tidyverse_1.1.1    reshape2_1.4.2     zoo_1.8-0         
> [7] hms_0.3            forcats_0.2.0      gridExtra_2.2.1    readxl_1.0.0       scales_0.4.1.9002  openxlsx_4.0.17   
> [13] lazyeval_0.2.0     xtable_1.8-2       fst_0.7.3          bindrcpp_0.2       stringr_1.2.0      readr_1.1.1       
> [19] dplyr_0.7.2        lubridate_1.6.0    ggplot2_2.2.1.9000
> 
> loaded via a namespace (and not attached):
>   [1] Rcpp_0.12.12      cellranger_1.1.0  compiler_3.4.1    git2r_0.19.0      plyr_1.8.4        bindr_0.1        
> [7] digest_0.6.12     jsonlite_1.5      nlme_3.1-131      lattice_0.20-35   memoise_1.1.0     gtable_0.2.0     
> [13] pkgconfig_2.0.1   rlang_0.1.1       psych_1.7.5       curl_2.8.1        parallel_3.4.1    haven_1.1.0      
> [19] xml2_1.1.1        withr_2.0.0       httr_1.2.1        devtools_1.13.2   glue_1.1.1        data.table_1.10.4
> [25] R6_2.2.2          foreign_0.8-69    modelr_0.1.1      magrittr_1.5      rvest_0.3.2       mnormt_1.5-5     
> [31] assertthat_0.2.0  colorspace_1.3-2  stringi_1.1.5     munsell_0.4.3     broom_0.4.2

**Comment by MarcusKlik** [comment]
Hi @eipi10, thanks for reporting your issue. Indeed, I see that `fst` preserves the `factor` attribute, but not the `ordered` class attribute:

``` r
library(fst)
dat = data.frame(x = ordered(c(LETTERS[c(1,1,2,4,1,3,4,3)])))
print(class(dat$x))
#> [1] "ordered" "factor"

write.fst(dat, "test.fst", compress=100)
dat.fst = read.fst("test.fst")
print(class(dat.fst$x))
#> [1] "factor"
```

Good find and I will make sure this is fixed before the next release, thanks!

**Comment by MarcusKlik** [comment]
Also, having a ordered `factor` column means that the table has at least a single key. This should be visible as a key when the table is returned as a `data.table` (in addition to the ordered `factor` column).

**Comment by eipi10** [comment]
Thanks Marcus. And thanks for a great package.

**Comment by MarcusKlik** [comment]
Hi @eipi10, `ordered factors` are now preserved across a write / read cycle as shown in this example (slight modification from your code):

``` r
dt = data.frame(x = ordered(c(LETTERS[c(1,1,2,4,1,3,4,3)])))  # ordered factor
fst::fstwrite(dt, "test.fst", compress = 100)
dt_read = fst::fstread("test.fst")

identical(dt, dt_read)
#> [1] TRUE
```

And the class of the retrieved `ordered factor` column is now set to `c('ordered', 'factor')`:

``` r
str(dt)
#> 'data.frame':    8 obs. of  1 variable:
#>  $ x: Ord.factor w/ 4 levels "A"<"B"<"C"<"D": 1 1 2 4 1 3 4 3

str(dt_read)
#> 'data.frame':    8 obs. of  1 variable:
#>  $ x: Ord.factor w/ 4 levels "A"<"B"<"C"<"D": 1 1 2 4 1 3 4 3
```

Behind the scenes, the `fstcore` C++ library now has an additional column attribute `FACTOR_ORDERED` for base type `FACTOR` to indicate that the levels are ordered (see [this](https://github.com/fstpackage/fst/blob/36eaaecc4f5c0f3eb7ab2e0a9f30eb5688573b34/src/fstcore/interface/ifstcolumn.h#L46-L78) code).

Thanks again for filing the issue and for using `fst`!

**Comment by eipi10** [comment]
Thanks Marcus!
