### ISSUE TITLE
Fix UBSAN and ASAN warnings

### ISSUE THREAD

**Issue by fstpackage** [fstpackage/fst#8]
By following the steps taken in [this dockerfile](https://github.com/rocker-org/r-devel-san-clang/blob/master/Dockerfile) on a fresh Ubuntu install.

**Comment by MarcusKlik** [comment]
Resolve Valgrind warnings as well by using the R dev build with sanitizer support on Docker.

**Comment by MarcusKlik** [comment]
All warnings have been resolved except some very specific `Rcpp` warnings:

```
/usr/local/lib/R/site-library/Rcpp/include/Rcpp/routines.h:80:20: runtime error: call to function Rcpp::internal::enterRNGScope() through pointer to incorrect function type 'unsigned long (*)()'
/tmp/RtmpsjU7hQ/R.INSTALL93ae2ccfb6/Rcpp/src/api.cpp:72: note: Rcpp::internal::enterRNGScope() defined here
SUMMARY: AddressSanitizer: undefined-behavior /usr/local/lib/R/site-library/Rcpp/include/Rcpp/routines.h:80:20 in 
/usr/local/lib/R/site-library/Rcpp/include/Rcpp/routines.h:86:20: runtime error: call to function Rcpp::internal::exitRNGScope() through pointer to incorrect function type 'unsigned long (*)()'
/tmp/RtmpsjU7hQ/R.INSTALL93ae2ccfb6/Rcpp/src/api.cpp:79: note: Rcpp::internal::exitRNGScope() defined here
SUMMARY: AddressSanitizer: undefined-behavior /usr/local/lib/R/site-library/Rcpp/include/Rcpp/routines.h:86:20 in 
```

I don't think that is a warning specific to `fst`, it shows on some `Rcpp` [build logs](https://www.stats.ox.ac.uk/pub/bdr/memtests/clang-UBSAN/Rcpp/build_vignettes.log) as well.

Basically, the sanitizer triggers this warning every time a `Rcpp` wrapped function is called from `R`.
