### ISSUE TITLE
Consistent naming of fst methods

### ISSUE THREAD

**Issue by MarcusKlik** [fstpackage/fst#94]
Currently, methods in the `fst` package have inconsistent naming. It would be better to change the public package interface in:

* `read_fst`
* `write_fst`
* `compress_fst`
* `decompress_fst`
* `hash_fst`
* `metadata_fst`
* `threads_fst`
* `bind_rows_fst` (_future addition_)
* `bind_cols_fst` (_future addition_

With these names, we adhere to the style implemented by the `lintr` package and offer a consistent interface (`lintr` [is used in the package unit tests](../blob/develop/tests/testthat/test.lintr.R) to enforce styling).

**Comment by Brinkhuis** [comment]
Nice, looking forward to the 0.8 release!

**Comment by MarcusKlik** [comment]
Thanks @Brinkhuis for a helpful discussion on `fst`'s public interface!

**Comment by MarcusKlik** [comment]
The public interface of `fst` has now changed:

``` r
library(fst)

cat(paste0(ls("package:fst"), collapse = "\n"))
#> compress_fst 
#> decompress_fst 
#> fst.metadata 
#> hash_fst 
#> metadata_fst 
#> read.fst 
#> read_fst 
#> threads_fst 
#> write.fst 
#> write_fst
```

The previously used methods `write.fst`, `read.fst` and `fst.metadata` will still be available for now, but should be marked as deprecated at some point in the future.
