### ISSUE TITLE
Error on empty tables using `write_fst`

### ISSUE THREAD

**Issue by arunsrinivasan** [fstpackage/fst#99]
```
require(data.table)
require(fst) # devel
dt <- data.table(x=1, y=Sys.time())[0]
dt
# Empty data.table (0 rows) of 2 cols: x,y

write_fst(dt, tempfile())
# Error in fststore(normalizePath(path, mustWork = FALSE), x, as.integer(compress),  : 
#   The dataset contains no data
```
It'd be useful to have both empty (0-row) and null data.tables/frames (0-row and 0-col) as fst files as well, along with the table's attributes.

**Comment by MarcusKlik** [comment]
Hi @arunsrinivasan, yes that would be nice, your request is also shortly discussed in #47. To store only column meta data would be very useful, especially when we implement row binding (where the first chunk can be empty if a series is stored).

What would be the added benefit of storing tables with 0 rows and columns?

thanks!

**Comment by arunsrinivasan** [comment]
It's mostly for convenience. Since previous code written using `rda` format doesn't have this issue, it'd be just consistent, allowing easier transition. Also, cases where data is intermittently obtained via streaming might have cases where no data was available for a particular time frame.

It avoids having to have a `if (nrow(...) > 0L) write_fst(...)` and `if (file.exists(...))` logic. Even if data wasn't there, having the attributes provide information about when data was last read / written, for example, could be helpful as well.

**Comment by shrektan** [comment]
+1 for this feature, thanks.

**Comment by arunsrinivasan** [comment]
This is one of the main enhancements that'd be really nice to have for us (and that blocks us from switching to `fst`). Is there a time frame for this? I can try and see if it's a relatively simple fix, if you could point me to the right part of the code :-).

**Comment by MarcusKlik** [comment]
Hi @arunsrinivasan, thanks for asking, yes I agree it's long overdue and not too much work! I'll make sure zero-row (and column) tables will be available soon, sorry to keep you waiting!

**Comment by arunsrinivasan** [comment]
@MarcusKlik thank you very much!

**Comment by nfillmore** [comment]
Agreed, this is such an important feature. The main problem with not allowing zero-row tables is that it requires adding otherwise unnecessary special cases for situations where, although there usually are rows in the table, it can happen that there are not due to e.g. there being no matches to a query.

Example: I am caching intermediate query results in fst files. The presence of the cached fst file is used to determine whether to run the query or load from the cached file. But, with small test datasets, sometimes a particular intermediate result has no entries. The zero-row prohibition means I need to find another way to signal that a query has been run and cached already, which is annoying.

Thank you for this amazing library!

**Comment by MarcusKlik** [comment]
Hi @nfillmore, thanks and I fully agree!

This is a very important feature required to better 'mimic' a dataset in memory with the contents of a _fst_ file. You should be able to store any (intermediate) dataset to disk without the need of additional code to handle special cases like zero rows or columns.

Also, as you and @arunsrinivasan mention, it's crucial for easy transitioning of existing code into code that uses `fst` to store (intermediate) results.

**Comment by nathaneastwood** [comment]
+1 here from me too @MarcusKlik. I've come up against this problem in my code today and will have to make use of `if (nrow(x) > 0L) write_fst(...)` for now.

**Comment by MarcusKlik** [comment]
Hi @nathaneastwood, thanks for sharing that, this feature is definitely scheduled for the next release!

**Comment by djvanderlaan** [comment]
+1!

For me the workaround is currently to redefine `write_fst` and `read_fst` to store the data as a RDS file when the `data.frame` is empty:

```
write_fst <- function(x, path, ...) {
  loadNamespace("fst")
  if (nrow(x) == 0) {
    warning("x is empty; writing RDS.")
    saveRDS(x, file = path)
  } else {
    fst::write_fst(x, path, ...)
  }
}

read_fst <- function(path, ..., columns = NULL, as.data.table = FALSE) {
  if (as.data.table) loadNamespace("data.table")
  loadNamespace("fst")
  file_is_fst <- FALSE
  try({
    tmp <- fst::read_fst(path, columns = columns, as.data.table = as.data.table, ...)
    file_is_fst <- TRUE
  }, silent = TRUE)
  if (!file_is_fst) {
    warning("File is not a fst file. Trying readRDS.")
    tmp <- readRDS(path)
    if (as.data.table) {
      tmp <- data.table::as.data.table(tmp)
      if (!is.null(columns)) tmp <- tmp[ , ..columns, drop = FALSE]
    } else  if (!is.null(columns)) {
      tmp <- tmp[ , columns, drop = FALSE]
    }
  }
  tmp
}
```

**Comment by MarcusKlik** [comment]
Hi @djvanderlaan,

thanks for reporting the issue and sharing your code!

I've pushed some updates to allow for zero-row tables of all available column types. It would be great if you can test the latest dev and see if it works for your use-case!

You can now do:

``` r
library(bit64)
library(fst)
library(nanotime)
library(testthat)

difftime_mode <- function(mode = "double") {
  vec <- (Sys.time() + 1) - Sys.time()
  mode(vec) <- mode
  vec[0]
}

x <- data.frame(
  Xint = integer(0),
  Ylog = logical(0),
  Zdoub = double(0),
  Qchar = character(0),
  Ordered = ordered(sample(LETTERS, 26, replace = TRUE))[0],
  Date = as.Date("2019-01-01")[0],
  Integer64 = as.integer64(2345612345679)[0],
  Nanotime = nanotime(1000000)[0],
  Raw = as.raw(255)[0],
  Difftime = difftime_mode(),
  DiffTime_int = difftime_mode("integer"),
  WFact = factor(sample(LETTERS, 26, replace = TRUE))[0],
  WFactNA = factor(NA)[0],
  stringsAsFactors = FALSE
)

# write and read cycle
fst_file <- tempfile(, fileext = ".fst")
write_fst(x, fst_file)
y <- read_fst(fst_file)

expect_equal(x, y)
```

thanx!

**Comment by willemvdb42** [comment]
I've just downloaded the development version, and saving empty dataframes now works for me.

Thanks!

**Comment by MarcusKlik** [comment]
great, thanks for testing!

**Comment by nfillmore** [comment]
Thank you so much!
Our team uses the fst library every day

**Comment by willemvdb42** [comment]
@MarcusKlik do you know when this feature would be implemented in the next CRAN package version?

**Comment by MarcusKlik** [comment]
Hi @willemvdb42, I will publish a minor update soon to bring this feature to CRAN, thanks for your patience!

**Comment by andirey** [comment]
Hi, Mark!
Thanks for your great package "fst".
I now tested it to replaced "feather". But I also stuck with error for saving empty data tables.
Is it possible to make update on CRAN to re-install fst directly from CRAN (not dev version).
Thanks ahead!
Andrii

**Comment by MarcusKlik** [comment]
Hi @andirey, I will try to get the update out soon, thanks for your patience!

**Comment by andirey** [comment]
Thanks, Mark! I will be waiting for it, really!

**Comment by shoonlee** [comment]
Hi Mark,
I'm really enjoying this great package! Thank you!

I also have the same issue. Removed earlier version and installed the dev version, but the same issue persists (mac os). Saving empty data set is not working both with the example code you provided and my user-case. It'd be great if this could be fixed soon. Thanks!!

**Comment by shoonlee** [comment]
Hi Mark! Thanks for a fantastic package. It's great to have an empty data writing feature, which I find most helpful when running a function over 50 states and some of them have 0 observations a posteriori. 

Related to that, is it possible to add a feature that reads in an empty file? Again, for me, it would be most helpful when reading in files from 50 states with a few empty ones. When I tried it, R throws an error message as the following:

    "Error in read_fst("AK_cleaned_5yrs.fst") : Row selection is out of range."

Thank you!

**Comment by MarcusKlik** [comment]
Hi @shoonlee, thanks for posting your question! I'm not sure I understand the exact code you are running, could you post it?

Reading an empty file should be possible now, as in:

``` r
tmp_fst <- tempfile()

# write empty table to disk
data.frame(X = integer(0)) %>%
  write_fst(tmp_fst)

# read it again
tmp_fst %>%
  read_fst()
#> [1] X
#> <0 rows> (or 0-length row.names)
```

**Comment by shoonlee** [comment]
Hi Mark, thanks for your reply. Upon double cheking, it was due to a silly mistake on my side. Sorry to bother you.

**Comment by MarcusKlik** [comment]
Hi @shoonlee, no problem, thanks for getting back on that and letting us know!

**Comment by arunsrinivasan** [comment]
Hi @MarcusKlik, excited to see this FR implemented. However it still doesn't work on `NULL` tables.

```r
fst::write_fst(data.frame(), temp_file()) # v0.9.2
# Error in fst::write_fst(data.frame(), tempfile()) : 
#   Your dataset needs at least one column.
```

`save()` handles this quite the same as empty/0-row tables. What do you think?

**Comment by fstpackage** [comment]
Hi @arunsrinivasan, and I though we tackled this one :-)

Yes you're very right, serialization behavior of `NULL` tables should be equal to `save()`, thanks for reporting!

**Comment by MarcusKlik** [comment]
Hi @arunsrinivasan, `NULL` tables are now supported directly in the _fst_ format:

``` r
path <- tempfile()

# special tables
zero_rows <- data.frame(X = integer(0), Y = double(0))
zero_cols <- data.frame()


# zero-row table with multiple columns
fst::write_fst(zero_rows, path)
testthat::expect_equal(zero_rows, fst::read_fst(path))

# zero-column table
fst::write_fst(zero_cols, path)
testthat::expect_equal(zero_cols, fst::read_fst(path))
```

with this binary implementation it is possible to store table attributes if required as a future enhancement.

Note that you will need the [dev version](https://github.com/fstpackage/fstcore#installation) of the `fstcore` package to make this work!
